Rewritten `bin/git-istash` to use `get_options`
This removes a few constraints on what order the arguments has to be
passed to the main script. Now, the only limit is that options specific
to a sub-command must be after anything that the main script can parse.
(E.g. now you can write `git istash --continue pop` instead of the usual
`git istash pop --continue`.)
I'm not sure whether this will make a noticeable difference for an
average user, but at least the code doesn't use so many awkward regexes,
and option abbreviations work correctly.

diff --git a/bin/git-istash b/bin/git-istash
--- a/bin/git-istash
+++ b/bin/git-istash
@@ -2,6 +2,8 @@
 
 set -eu
 
+. "$(dirname "$0")/../lib/git-istash/get_options"
+
 min_git_version='2.42.0'
 min_git_version_regex='2\.(4[2-9]|[5-9][0-9]|[1-9][0-9]{2,})(\..+)?'
 
@@ -47,6 +49,10 @@ print_version() {
 	printf 'Requires Git in version at least %s\n' "$min_git_version"
 }
 
+is_option_alias() { # subcommand
+	printf '%s\n' "$1" | grep -Eqx -- 'c(o(n(t(i(n(ue?)?)?)?)?)?)?|abort|quit'
+}
+
 exec_subcommand() { # subcommand [arguments...]
 	subcommand="$1"
 	shift
@@ -82,69 +88,140 @@ show_manual() {
 	return 1
 }
 
-set +u
-skip_version_check=n
-if [ "$1" = '--_skip-version-check_' ]
-then
+getopt_short_options='ch'
+getopt_long_options='_skip-version-check_,abort,color:,continue,help,man,quit,version'
+subcommand=''
+needs_additional_pass=y
+while [ "$needs_additional_pass" = y ]
+do
+	normalized_options="$(get_options -U "$getopt_short_options" "$getopt_long_options" "$@")"
+	eval set -- "$normalized_options"
+	known_options_at_front=''
+	while [ "$1" != '--' ]
+	do
+		known_options_at_front="$known_options_at_front $(printf '%s' "$1" | escape_for_shell)"
+		shift
+	done
 	shift
-	skip_version_check=y
-fi
-if [ "$1" = '--help' ] || [ "$2" = '--help' ] || [ "$1" = '--man' ] || [ "$2" = '--man' ]
-then
-	if show_manual
+	if [ $# -ne 0 ] && printf '%s' "$1" | grep -E -q '^[^-]'
 	then
-		exit 0
+		if is_option_alias "$1"
+		then
+			if [ "$(printf '%s' "$1" | head -c1)" = 'c' ]
+			then
+				shift
+				set -- 'continue' "$@"
+			fi
+			known_options_at_front="$known_options_at_front $(printf -- '--%s' "$1" | escape_for_shell)"
+			needs_additional_pass=y
+		else
+			subcommand="$1"
+			needs_additional_pass=n
+		fi
+		shift
 	else
-		if [ "$1" = '--help' ] || [ "$1" = '--man' ]
+		needs_additional_pass=n
+	fi
+	eval set -- "$known_options_at_front" '"$@"'
+	unset known_options_at_front
+done
+unset needs_additional_pass
+normalized_options="$(get_options -U "$getopt_short_options" "$getopt_long_options" "$@")"
+eval set -- "$normalized_options"
+
+skip_version_check=n
+options_to_put_back=''
+continuation_option=''
+while true
+do
+	case "$1" in
+	--_skip-version-check_)
+		skip_version_check=y
+		;;
+	--color)
+		shift
+		options_to_put_back="$options_to_put_back --color $(printf -- '--%s' "$1" | escape_for_shell)"
+		;;
+	-h)
+		if [ -z "$subcommand" ] || is_option_alias "$subcommand"
 		then
 			print_help
 			exit 0
 		else
-			eval set -- "$1" -h
+			exec_subcommand "$subcommand" '-h'
 		fi
-	fi
-elif [ "$1" = '-h' ] || [ "$1" = '--help' ]
-then
-	print_help
-	exit 0
-elif [ "$1" = '--version' ] || [ "$2" = '--version' ]
-then
-	print_version
-	exit 0
-elif printf '%s\n' "$1" | grep -Eqx -- '-c|(--)?c(o(n(t(i(n(ue?)?)?)?)?)?)?|--ab(o(r(t)?)?)?|abort|--q(u(it?)?)?|quit'  # Not a pretty solution but one that doesn't require knowing all options of every subcommand. (Although, it needs manual updating when something changes.)
-then
-	set -u
-	continuation_option="$1"
-	if printf '%s\n' "$continuation_option" | grep -qEv '^-'
-	then
-		continuation_option="--$continuation_option"
-	fi
-	shift
-	. "$(dirname "$0")/../lib/git-istash/git-istash-commons"
-	data_files="$(find_data_files)"
-	case "$data_files" in
-		nothing)
-			printf 'error: no istash operation in progress\n' 1>&2
-			exit 1
-			;;
-		apply)
-			exec_subcommand 'apply' "$continuation_option" "$@"
-			;;
-		pop)
-			exec_subcommand 'pop' "$continuation_option" "$@"
-			;;
-		error-*)
-			if printf '%s' "$continuation_option" | grep -Exq -- '--q(u(it?)?)?'
+		;;
+	--help)
+		if [ "$1" = '--help' ]
+		then
+			exec git istash --help
+		fi
+		;;
+	--man)
+		if show_manual
+		then
+			exit 0
+		else
+			if [ -z "$subcommand" ]
 			then
-				exec_subcommand "$(printf '%s' "$data_files" | tail -c+7)" "$continuation_option" "$@"
+				print_help
+				exit 0
 			else
-				print_error_for_data_files_check "$data_files" 'push'
-				exit 1
+				shift
+				set -- '-h'
+				continue
 			fi
-			;;
+		fi
+		;;
+	--version)
+		print_version
+		exit 0
+		;;
+	-c|--continue|--abort|--quit)
+		options_to_put_back="$options_to_put_back $(printf '%s' "$1" | escape_for_shell)"
+		continuation_option="$1"
+		;;
+	--)
+		shift
+		break
+		;;
 	esac
+	shift
+done
+eval set -- "$options_to_put_back" '"$@"'
+
+if [ -z "$subcommand" ]
+then
+	if [ -z "$continuation_option" ]
+	then
+		subcommand='push'
+		set -- '--_implicit-push_' "$@"
+	else
+		. "$(dirname "$0")/../lib/git-istash/git-istash-commons"
+		data_files="$(find_data_files)"
+		case "$data_files" in
+			nothing)
+				printf 'error: no istash operation in progress\n' 1>&2
+				exit 1
+				;;
+			apply)
+				subcommand='apply'
+				;;
+			pop)
+				subcommand='pop'
+				;;
+			error-*)
+				if [ "$continuation_option" = '--quit' ]
+				then
+					subcommand="$(printf '%s' "$data_files" | tail -c+7)"
+				else
+					print_error_for_data_files_check "$data_files" 'push'
+					exit 1
+				fi
+				;;
+		esac
+	fi
 fi
-set -u
 
 git_version="$(git --version | head -n 1 | grep -Eo '\<\S+$')"
 if [ "$skip_version_check" = n ] && ! printf '%s' "$git_version" | grep -Exq "$min_git_version_regex"
@@ -153,8 +230,4 @@ then
 	exit 1
 fi
 
-if [ $# -eq 0 ] || printf '%s' "$1" | grep -Eq '^-'
-then
-	set -- 'push' '--_implicit-push_' "$@"
-fi
-exec_subcommand "$@"
+exec_subcommand "$subcommand" "$@"
