Moved the Git version check higher
The Git version check is now very close to the beginning of the code, to
minimize the risk of the script tripping on some Git function before it
gets to it.

diff --git a/bin/git-istash b/bin/git-istash
--- a/bin/git-istash
+++ b/bin/git-istash
@@ -50,6 +50,46 @@ print_version() {
 	printf 'Requires Git in version at least %s\n' "$min_git_version"
 }
 
+if [ "${1-}" != '--_skip-version-check_' ]
+then
+	git_version="$(git --version | head -n 1 | grep -Eo '\<\S+$')"
+	# No color here or fancy utility functions because we don't know if they would work correctly.
+	version_regex='([0-9]+(\.[0-9]+){2})(\..+)?'
+	if ! printf '%s' "$git_version" | grep -Exq "$version_regex"
+	then
+		printf 'fatal: cannot check the version number of Git\n'
+		printf 'fatal: (it'\''s "%s"; it was expected to match "%s")\n' "$git_version" "$version_regex"
+		printf 'hint: minimum version required to safely run this is command "%s"\n' "$min_git_version"
+		printf 'hint: if you believe that your version is compatible, you can add the option\nhint: "--_skip-version-check_" as the first argument, at your own risk\n'
+		printf 'hint: (and consider reporting this)\n'
+		exit 1
+	fi
+	version_parts="$(
+		printf '%s' "$git_version" \
+		| sed -E "s/^$version_regex\$/\\1/" \
+		| tr '.' '\n'
+	)"
+	major="$(printf '%s' "$version_parts" | sed -En '1{p;q}')"
+	minor="$(printf '%s' "$version_parts" | sed -En '2{p;q}')"
+	patch="$(printf '%s' "$version_parts" | sed -En '3{p;q}')"
+	min_version_parts="$(printf '%s' "$min_git_version" | tr '.' '\n')"
+	min_major="$(printf '%s' "$min_version_parts" | sed -En '1{p;q}')"
+	min_minor="$(printf '%s' "$min_version_parts" | sed -En '2{p;q}')"
+	min_patch="$(printf '%s' "$min_version_parts" | sed -En '3{p;q}')"
+	if ! [ "$major" -eq "$min_major" ]
+	then
+		printf 'fatal: this script is developed and testes only for Git in version %i\n' "$min_major"
+		exit 1
+	fi
+	if ! { [ "$minor" -gt "$min_minor" ] || { [ "$minor" -eq "$min_minor" ] && [ "$patch" -ge "$min_patch" ] ; } ; }
+	then
+		printf 'fatal: the current Git version (%s) is less than minimum required (%s)\n' "$git_version" "$min_git_version"
+		exit 1
+	fi
+else
+	shift
+fi 1>&2
+
 is_option_alias() { # subcommand
 	printf '%s\n' "$1" | grep -Eqx -- 'c(o(n(t(i(n(ue?)?)?)?)?)?)?|abort|quit'
 }
@@ -89,10 +129,9 @@ show_manual() {
 }
 
 getopt_short_options='chqV'
-getopt_long_options='_skip-version-check_,abort,color::,no-color,continue,help,man,quiet,quit,version'
+getopt_long_options='abort,color::,no-color,continue,help,man,quiet,quit,version'
 normalized_options="$(get_options_color -U "$getopt_short_options" "$getopt_long_options" "$@")"
 eval set -- "$normalized_options"
-skip_version_check=n
 is_quiet=n
 options_to_put_back=''
 continuation_option=''
@@ -100,9 +139,6 @@ subcommand=''
 while true
 do
 	case "$1" in
-	--_skip-version-check_)
-		skip_version_check=y
-		;;
 	--color)
 		shift
 		set_color_for_all "$1"
@@ -213,43 +249,5 @@ then
 		esac
 	fi
 fi
-
-git_version="$(git --version | head -n 1 | grep -Eo '\<\S+$')"
-if [ "$skip_version_check" = n ]
-then
-	# No color here or fancy utility functions because we don't know if they would work correctly.
-	version_regex='([0-9]+(\.[0-9]+){2})(\..+)?'
-	if ! printf '%s' "$git_version" | grep -Exq "$version_regex"
-	then
-		printf 'fatal: cannot check the version number of Git\n'
-		printf 'fatal: (it'\''s "%s"; it was expected to match "%s")\n' "$git_version" "$version_regex"
-		printf 'hint: minimum version required to safely run this is command "%s"\n' "$min_git_version"
-		printf 'hint: if you believe that your version is compatible, you can add the option\nhint: "--_skip-version-check_" at your own risk '
-		printf '(and consider reporting this)\n'
-		exit 1
-	fi
-	version_parts="$(
-		printf '%s' "$git_version" \
-		| sed -E "s/^$version_regex\$/\\1/" \
-		| tr '.' '\n'
-	)"
-	major="$(printf '%s' "$version_parts" | sed -En '1{p;q}')"
-	minor="$(printf '%s' "$version_parts" | sed -En '2{p;q}')"
-	patch="$(printf '%s' "$version_parts" | sed -En '3{p;q}')"
-	min_version_parts="$(printf '%s' "$min_git_version" | tr '.' '\n')"
-	min_major="$(printf '%s' "$min_version_parts" | sed -En '1{p;q}')"
-	min_minor="$(printf '%s' "$min_version_parts" | sed -En '2{p;q}')"
-	min_patch="$(printf '%s' "$min_version_parts" | sed -En '3{p;q}')"
-	if ! [ "$major" -eq "$min_major" ]
-	then
-		printf 'this script is developed and testes only for Git in version %i\n' "$min_major"
-		exit 1
-	fi
-	if ! { [ "$minor" -gt "$min_minor" ] || { [ "$minor" -eq "$min_minor" ] && [ "$patch" -ge "$min_patch" ] ; } ; }
-	then
-		printf 'the current Git version (%s) is less than minimum required (%s)\n' "$git_version" "$min_git_version"
-		exit 1
-	fi
-fi 1>&2
 
 exec_subcommand "$subcommand" "$@"
