Changed the scripts output to mostly correct state
Almost all the output was redone. This are broad strokes for now so some
minor thing may still be not quite right but generally the output now
looks like intended. (So it's similar to output of normal Git commands.)

diff --git a/bin/git-istash b/bin/git-istash
--- a/bin/git-istash
+++ b/bin/git-istash
@@ -52,7 +52,8 @@ exec_subcommand() { # subcommand [arguments...]
 	subcommand_path="$(dirname "$0")/../lib/git-istash/git-istash-$subcommand"
 	if [ ! -f "$subcommand_path" ] || [ ! -x "$subcommand_path" ]
 	then
-		printf 'git-istash: "%s" is not a sub-command. See "git istash --help".\n' "$subcommand" 1>&2
+		printf 'error: subcommand wasn'\''t specified; '\''push'\'' can'\''t be assumed due to unexpected token '\''%s'\''\n' "$subcommand" 1>&2
+		printf 'hint: pathspecs for an implicit '\''push'\'' subcommand must be preceded by '\''--'\''\n' 1>&2
 		return 1
 	fi
 	exec sh "$subcommand_path" "$@"
@@ -123,7 +124,7 @@ then
 	data_files="$(find_data_files)"
 	case "$data_files" in
 		nothing)
-			printf 'fatal: There doesn'\''t seem to be any operation in progress.\n' 1>&2
+			printf 'error: no istash operation in progress\n' 1>&2
 			exit 1
 			;;
 		apply)
@@ -137,7 +138,7 @@ then
 			then
 				exec_subcommand "$(printf '%s' "$data_files" | tail -c+7)" "$continuation_option" "$@"
 			else
-				printf 'fatal: The operation in progress seems damaged.\n' 1>&2
+				printf 'fatal: the operation in progress seems to be broken\n' 1>&2
 				exit 1
 			fi
 			;;
diff --git a/lib/git-istash/git-istash-apply b/lib/git-istash/git-istash-apply
--- a/lib/git-istash/git-istash-apply
+++ b/lib/git-istash/git-istash-apply
@@ -39,7 +39,8 @@ save_data() {
 load_target_data() { # subcommand
 	if [ "$(wc -l <"$target_data_file")" -ne 1 ]
 	then
-		printf 'fatal: "%s" should have exactly 1 line.\n' "$target_data_file" 1>&2
+		printf 'fatal: '\''git istash %s'\'' seems to be running but the data files are broken\n' "$(get_sub_command_name)" 1>&2
+		printf 'fatal: '\''%s'\'' doesn'\''t have exactly 1 line\n' "$target_data_file" 1>&2
 		print_quit_hint_for_new_operation "$1"
 		return 1
 	fi
@@ -53,7 +54,8 @@ load_target_data() { # subcommand
 	fi
 	if ! git rev-parse --quiet --verify "$current_branch^{commit}" 1>/dev/null
 	then
-		printf 'fatal: "%s" says "%s" but there is no such commit.\n' "$target_data_file" "$current_branch" 1>&2
+		printf 'fatal: '\''git istash %s'\'' seems to be running but the data files are broken\n' "$(get_sub_command_name)" 1>&2
+		printf 'fatal: '\''%s'\'' contains an invalid commit hash\n' "$target_data_file" 1>&2
 		print_quit_hint_for_new_operation "$1"
 		return 1
 	fi
@@ -65,14 +67,16 @@ load_target_data() { # subcommand
 load_working_dir_data() { # subcommand
 	if [ "$(wc -l <"$working_dir_sha_file")" -ne 1 ]
 	then
-		printf 'fatal: "%s" should have exactly 1 line.\n' "$working_dir_sha_file" 1>&2
+		printf 'fatal: '\''git istash %s'\'' seems to be running but the data files are broken\n' "$(get_sub_command_name)" 1>&2
+		printf 'fatal: '\''%s'\'' doesn'\''t have exactly 1 line\n' "$working_dir_sha_file" 1>&2
 		print_quit_hint_for_new_operation "$1"
 		return 1
 	fi
 	working_dir_changes_sha="$(cat "$working_dir_sha_file")"
 	if ! git rev-parse --quiet --verify "$working_dir_changes_sha^{commit}" 1>/dev/null
 	then
-		printf 'fatal: "%s" says "%s" but there is no such commit.\n' "$working_dir_sha_file" "$working_dir_changes_sha" 1>&2
+		printf 'fatal: '\''git istash %s'\'' seems to be running but the data files are broken\n' "$(get_sub_command_name)" 1>&2
+		printf 'fatal: '\''%s'\'' contains an invalid commit hash\n' "$working_dir_sha_file" 1>&2
 		print_quit_hint_for_new_operation "$1"
 		return 1
 	fi
@@ -99,12 +103,10 @@ put_files_into_working_copy() { # untracked_changes_sha non_staged_changes_sha s
 
 end_with_rebase_problem() {
 	{
-		printf '\n'
 		printf_color 2 '\033[33m'
 		sub_command_name="$(get_sub_command_name)"
-		printf 'hint: Disregard all hints above about using "git rebase".\n'
-		printf 'hint: Use "git istash %s --continue" after fixing conflicts.\n' "$sub_command_name"
-		printf 'hint: To abort and get back to the state before "git istash %s", run "git istash %s --abort".\n' "$sub_command_name" "$sub_command_name"
+		printf 'hint: use '\''git istash --continue'\'' after fixing the conflicts\n'
+		printf 'hint: or, to undo everything '\''git istash %s'\'' did, run '\''git istash --abort'\''\n' "$sub_command_name"
 		printf_color 2 '\033[39m'
 	} 1>&2
 	return 2
@@ -113,7 +115,7 @@ end_with_success() {
 	if { [ "$curr_branch_type" != 'orphan' ] && [ "$(git rev-parse HEAD~6)" != "$(git rev-parse "$current_branch")" ] ; } \
 		|| { [ "$curr_branch_type" = 'orphan' ] && [ "$(git rev-list --no-walk --count HEAD~6^@)" != '0' ] ; }
 	then
-		printf 'fatal: HEAD is not in the correct position after rebasing.\n' 1>&2
+		printf 'fatal: HEAD is not in the correct position after rebasing\n' 1>&2
 		return 1
 	fi
 	untracked_changes_sha="$(git rev-parse HEAD~0)"
@@ -138,21 +140,24 @@ end_with_success() {
 	esac
 	put_files_into_working_copy "$untracked_changes_sha" "$non_staged_changes_sha" "$staged_changes_sha"
 	delete_data
-	printf '\nSuccessfully applied the stash\n'
 	printf 'Stash of the old working dir: %s\n' "$(prepare_stash_of_working_dir)"
+	if [ "$is_pop" = n ]
+	then
+		printf '\nSuccessfully applied the stash\n'
+	fi
 }
 
 print_quit_hint() { # subcommand
-	printf 'hint: or run "git istash %s --quit" to forcefully cancel it.\n' "$1"
+	printf 'hint: or run '\''git istash --quit'\'' to forcefully cancel it\n'
 }
 
 print_quit_hint_for_new_operation() { # subcommand
 	printf_color 2 '\033[33m'
 	if [ "$1" = "$(get_sub_command_name)" ]
 	then
-		printf 'hint: Fix the problem and finish that operation before starting a new one\n'
+		printf 'hint: fix the problem and finalize that operation before starting a new one\n'
 	else
-		printf 'hint: Fix the problem and finish that operation before starting "git istash apply"\n'
+		printf 'hint: fix the problem and finalize that operation before starting '\''istash apply'\''\n'
 	fi
 	print_quit_hint "$1"
 	printf_color 2 '\033[39m'
@@ -160,7 +165,7 @@ print_quit_hint_for_new_operation() { # subcommand
 
 print_quit_hint_for_resumed_operation() { # subcommand
 	printf_color 2 '\033[33m'
-	printf 'hint: Fix problems and rerun "git istash %s --abort"\n' "$(get_sub_command_name)"
+	printf 'hint: fix the problems and rerun the operation with '\''git istash --abort'\''\n'
 	print_quit_hint "$(get_sub_command_name)"
 	printf_color 2 '\033[39m'
 } 1>&2
@@ -173,7 +178,7 @@ check_data_files() { # resume quit
 			if [ "$2" = y ] ; then return 0 ; fi
 			{
 				printf_color 2 '\033[33m'
-				printf 'error: There is currently a istash %s in progress.\n' "$operation_in_progress"
+				printf 'error: there is currently '\''git istash %s'\'' in progress\n' "$operation_in_progress"
 				printf_color 2 '\033[39m'
 			} 1>&2
 			return 1
@@ -182,8 +187,8 @@ check_data_files() { # resume quit
 			if [ "$1" = y ] || [ "$2" = y ] ; then return 0 ; fi
 			{
 				printf_color 2 '\033[33m'
-				printf 'fatal: "git istash apply" is already in progress?\n'
-				printf 'hint: Use "git istash %s --continue" or "git istash %s --abort".\n' "$operation_in_progress" "$operation_in_progress"
+				printf 'error: '\''git istash apply'\'' is already in progress\n'
+				printf 'hint: use '\''git istash --continue'\'' or '\''git istash --abort'\''\n'
 				printf_color 2 '\033[39m'
 			} 1>&2
 			return 1
@@ -195,12 +200,15 @@ check_data_files() { # resume quit
 				printf_color 2 '\033[31m'
 				if [ -f "$(make_target_data_file_path)" ]
 				then
-					printf 'fatal: "git istash %s" seems to be in progress but "%s" is missing!\n' "$operation_in_progress" "$(make_working_dir_sha_file_path)"
+					printf 'fatal: '\''git istash %s'\'' seems to be running but the data files are broken\n' "$operation_in_progress" 1>&2
+					printf 'fatal: '\''%s'\'' is missing\n' "$(make_working_dir_sha_file_path)"
 				elif [ -f "$(make_working_dir_sha_file_path)" ]
 				then
-					printf 'fatal: "git istash %s" seems to be in progress but "%s" is missing!\n' "$operation_in_progress" "$(make_target_data_file_path)"
+					printf 'fatal: '\''git istash %s'\'' seems to be running but the data files are broken\n' "$operation_in_progress" 1>&2
+					printf 'fatal: '\''%s'\'' is missing\n' "$(make_target_data_file_path)"
 				else
-					printf 'fatal: "git istash %s" seems to be in progress but "%s" and "%s" are missing!\n' "$operation_in_progress" "$(make_target_data_file_path)" "$(make_working_dir_sha_file_path)"
+					printf 'fatal: '\''git istash %s'\'' seems to be running but the data files are broken\n' "$operation_in_progress" 1>&2
+					printf 'fatal: '\''%s'\'' and '\''%s'\'' are missing\n' "$(make_target_data_file_path)" "$(make_working_dir_sha_file_path)"
 				fi
 			} 1>&2
 			print_quit_hint_for_new_operation "$operation_in_progress"
@@ -208,7 +216,7 @@ check_data_files() { # resume quit
 			;;
 		nothing)
 			if [ "$1" = n ] && [ "$2" = n ] ; then return 0 ; fi
-			printf 'fatal: No istash apply in progress?\n' 1>&2
+			printf 'error: no istash apply in progress\n' 1>&2
 			return 1
 			;;
 	esac
@@ -319,27 +327,29 @@ do_abort() { # args...
 	git rebase --abort || true  # Errors are ignored because if rebase is not in progress, we still want to try to restore HEAD.
 	git reset --quiet --hard
 	succeeded_switch=n
+	exec 3>&1
 	case "$curr_branch_type" in
 		orphan)
 			git branch --quiet --delete --force "$current_branch"
-			if git switch --quiet --orphan "$current_branch"
+			if error_message="$(git switch --quiet --orphan "$current_branch" 2>&1 1>&3)"
 			then
 				succeeded_switch=y
 			fi
 			;;
 		normal)
-			if git switch --quiet "$current_branch"
+			if error_message="$(git switch --quiet "$current_branch" 2>&1 1>&3)"
 			then
 				succeeded_switch=y
 			fi
 			;;
 		detached)
-			if git switch --quiet --detach --quiet "$current_branch"
+			if error_message="$(git switch --quiet --detach --quiet "$current_branch" 2>&1 1>&3)"
 			then
 				succeeded_switch=y
 			fi
 			;;
 	esac
+	exec 3>&-
 	if [ "$succeeded_switch" = y ]
 	then
 		put_files_into_working_copy "$(git rev-parse "$working_dir_changes_sha~0")" "$(git rev-parse "$working_dir_changes_sha~1")" "$(git rev-parse "$working_dir_changes_sha~2")"
@@ -347,14 +357,14 @@ do_abort() { # args...
 		delete_data
 		if [ "$is_really_pop" = n ]
 		then
-			printf 'Aborted "git istash apply"\n' 1>&2
+			printf 'Successfully aborted '\''git istash apply'\''\n'
 		else
-			printf 'Aborted "git istash pop"\n' 1>&2
-		fi
+			printf 'Successfully aborted '\''git istash pop'\''\n'
+		fi 1>&2
 	else
 		{
-			printf '\n'
-			printf 'fatal: Failed to restore HEAD.\n'
+			printf 'fatal: failed to restore HEAD to initial position\n'
+			printf '%s\n' "$error_message"
 			print_quit_hint_for_resumed_operation
 		} 1>&2
 		return 1
@@ -371,7 +381,15 @@ do_quit() { # args...
 	fi
 	
 	git rebase --quit 2>/dev/null || true  # Errors are ignored because if rebase is not in progress or broken, we still want to remove the data files.
+	is_really_pop="$(if [ -f "$(make_stash_data_file_path)" ] ; then printf 'y' ; else printf 'n' ; fi)"
 	delete_data
+	
+	if [ "$is_really_pop" = n ]
+	then
+		printf 'Successfully quit '\''git istash apply'\''\n'
+	else
+		printf 'Successfully quit '\''git istash pop'\''\n'
+	fi 1>&2
 }
 
 do_apply() { # args...
@@ -425,22 +443,22 @@ do
 done
 if [ $continue_set = y ] && [ $abort_set = y ] && [ $quit_set = y ]
 then
-	printf 'error: You can choose continue, abort or quit at your discretion but the rule is that you can only have one.\n' 1>&2
+	printf 'error: you can choose continue, abort or quit at your discretion but the rule is that you can only have one\n' 1>&2
 	exit 1
 fi
 if [ $abort_set = y ] && [ $quit_set = y ]
 then
-	printf 'error: Either abort or quit; there is no middle road.\n' 1>&2
+	printf 'error: either abort or quit; there is no middle road\n' 1>&2
 	exit 1
 fi
 if [ $continue_set = y ] && [ $abort_set = y ]
 then
-	printf 'error: Unclear whether to continue aborting or to abort continuing.\n' 1>&2
+	printf 'error: unclear whether to continue aborting or to abort continuing\n' 1>&2
 	exit 1
 fi
 if [ $continue_set = y ] && [ $quit_set = y ]
 then
-	printf 'error: Unclear whether to continue quitting or to quit continuing.\n' 1>&2
+	printf 'error: unclear whether to continue quitting or to quit continuing\n' 1>&2
 	exit 1
 fi
 
diff --git a/lib/git-istash/git-istash-commons b/lib/git-istash/git-istash-commons
--- a/lib/git-istash/git-istash-commons
+++ b/lib/git-istash/git-istash-commons
@@ -77,46 +77,48 @@ check_args() { # max_free_args args...
 	shift 2
 	if [ $# -gt "$_max_free_args" ]
 	then
-		printf 'error: Too many arguments.\n' 1>&2
-		printf 'error: Type "git %s --help" for more information.\n' "$_script_name" 1>&2
+		printf 'error: too many arguments\n' 1>&2
+		printf 'hint: type '\''git %s --help'\'' for detailed information\n' "$_script_name" 1>&2
+		printf 'hint: or '\''git %s -h'\'' for a short help text\n' "$_script_name" 1>&2
 		return 1
 	fi
 }
 
 check_other_git_commands_state() {
+	other_git_command=''
 	git_dir="$(git rev-parse --git-dir)"
 	if [ -e "$git_dir/rebase-apply" ] || [ -e "$git_dir/rebase-merge" ]
 	then
-		printf 'error: There is currently a rebase in progress.\n' 1>&2
-		return 1
-	fi
-	if [ -e "$git_dir/CHERRY_PICK_HEAD" ]
+		other_git_command='rebase'
+	elif [ -e "$git_dir/CHERRY_PICK_HEAD" ]
 	then
-		printf 'error: There is currently a cherry-pick in progress.\n' 1>&2
-		return 1
-	fi
-	if [ -e "$git_dir/REVERT_HEAD" ]
+		other_git_command='cherry-pick'
+	elif [ -e "$git_dir/REVERT_HEAD" ]
 	then
-		printf 'error: There is currently a revert in progress.\n' 1>&2
-		return 1
-	fi
-	if [ -e "$git_dir/MERGE_HEAD" ]
+		other_git_command='revert'
+	elif [ -e "$git_dir/MERGE_HEAD" ]
 	then
-		printf 'error: There is currently a merge in progress.\n' 1>&2
-		return 1
-	fi
-	if [ -e "$git_dir/BISECT_START" ]
+		other_git_command='merge'
+	elif [ -e "$git_dir/BISECT_START" ]
 	then
-		printf 'error: There is currently a bisect in progress.\n' 1>&2
+		other_git_command='bisect'
+	fi
+	if [ -n "$other_git_command" ]
+	then
+		printf 'error: there is currently '\''git %s'\'' in progress\n' "$other_git_command" 1>&2
 		return 1
 	fi
 }
 
 check_data_files() {
 	current_operation="$(find_data_files)"
-	if [ "$current_operation" != 'nothing' ]
+	if printf '%s\n' "$current_operation" | grep -E -q '^error-'
 	then
-		printf 'error: There is currently an istash %s in progress.\n' "$current_operation" 1>&2
+		printf 'error: there is currently a broken '\''git istash %s'\'' in progress\n' "$(printf '%s' "$current_operation" | tail -c+7)" 1>&2
+		return 1
+	elif [ "$current_operation" != 'nothing' ]
+	then
+		printf 'error: there is currently '\''git istash %s'\'' in progress\n' "$current_operation" 1>&2
 		return 1
 	fi
 }
@@ -160,7 +162,7 @@ check_stash() { # stash
 	stash_commit="$(get_stash_commit "$1")"
 	if ! git rev-parse --quiet --verify "$stash_commit^{commit}" 1>/dev/null
 	then
-		printf 'fatal: There is no commit "%s".\n' "$stash_commit" 1>&2
+		printf 'error: no commit '\''%s'\''\n' "$stash_commit" 1>&2
 		return 1
 	fi
 	parents_num="$(git rev-list --no-walk --count "$stash_commit^@")"
diff --git a/lib/git-istash/git-istash-make-stash b/lib/git-istash/git-istash-make-stash
--- a/lib/git-istash/git-istash-make-stash
+++ b/lib/git-istash/git-istash-make-stash
@@ -140,7 +140,7 @@ check_pathspec() {
 			if [ "$good" = n ]
 			then
 				#shellcheck disable=SC2059
-				printf 'fatal: pathspec '\'"$ps"\'' did not match any files\n' 1>&2
+				printf 'error: pathspec '\'"$ps"\'' did not match any file(s)\n' 1>&2
 				return 1
 			fi
 		done
@@ -189,17 +189,19 @@ commit_changes() {
 		branch_name_for_msg='(no branch)'
 	fi
 	there_are_enough_changes="$allow_empty"
+	there_was_patch_message=n
 	
 	# staged (initial)
 	git commit --message="index on $branch_name_for_msg: $default_message (unfinished)" --allow-empty 1>/dev/null
 	
 	# unstaged
-	if [ -n "$patch_options" ]
-	then
-		printf '### Using the interactive patch for tracked files...' 1>&2
-	fi
 	if [ "$leave_unstaged" = n ]
 	then
+		if [ -n "$patch_options" ]
+		then
+			printf '### Using the interactive patch for tracked files...\n\n' 1>&2
+			there_was_patch_message=y
+		fi
 		if [ -z "$pathspec_file" ]
 		then
 			git --no-literal-pathspecs add --update $patch_options :/ 1>&2 2>/dev/null || true
@@ -240,7 +242,12 @@ commit_changes() {
 		fi
 		if [ -n "$patch_options" ]
 		then
-			printf '### Using the interactive patch for untracked files...' 1>&2
+			if [ "$there_was_patch_message" = y ]
+			then
+				printf '\n' 1>&2
+			fi
+			printf '### Using the interactive patch for untracked files...\n\n' 1>&2
+			there_was_patch_message=y
 		fi
 		if [ -z "$pathspec_file" ]
 		then
@@ -304,7 +311,11 @@ commit_changes() {
 	if [ "$there_are_enough_changes" = n ]
 	then
 		undo_commit_changes
-		printf 'fatal: There are no suitable changes to stash.\n' 1>&2
+		if [ "$there_was_patch_message" = y ]
+		then
+			printf '\n' 1>&2
+		fi
+		printf 'error: no suitable changes to stash\n' 1>&2
 		return 1
 	fi
 }
@@ -438,6 +449,41 @@ remove_temporary_branch() {
 	git switch --quiet --orphan "$current_branch"
 }
 
+print_summary() {
+	if [ "$there_was_patch_message" = y ]
+	then
+		printf '\n' 1>&2
+	fi
+	printf 'Saved '
+	{
+		if [ "$leave_unstaged" = n ]
+		then
+			printf 'working directory, '
+		fi
+		if [ "$leave_staged" = n ]
+		then
+			printf 'index state, '
+		fi
+		if [ "$include_untracked" = y ]
+		then
+			printf 'untracked files'
+			if [ "$include_ignored" = y ]
+			then
+				printf ' (including ignored)'
+			fi
+			printf ', '
+		elif [ "$include_ignored" = y ]
+		then
+			printf 'ignored files, '
+		fi
+		if [ "$leave_unstaged" = y ] && [ "$leave_staged" = y ] && [ "$include_untracked" = n ] && [ "$include_ignored" = n ]
+		then
+			printf 'nothing, '
+		fi
+	} | sed -E -e 's/, $/ /' -e 's/,([^,]+)$/ and\1/'
+	git rev-list --no-commit-header --format='%s' --max-count=1 "$stash_sha"
+} 1>&2
+
 make_stash() { # pathspecs...
 	check_data_files
 	check_other_git_commands_state
@@ -457,6 +503,7 @@ make_stash() { # pathspecs...
 	else
 		create_stash
 	fi
+	print_summary
 }
 
 getopt_short_options='ahklm:Su'
@@ -543,12 +590,12 @@ then
 fi
 if [ -n "$patch_options" ] && [ "$pathspec_from_file" = '-' ]
 then
-	printf 'Stdin cannot be assigned to both "--patch" and the pathspec.\n' 1>&2
+	printf 'error: stdin cannot be assigned to both '\''--patch'\'' and the pathspec\n' 1>&2
 	exit 1
 fi
 if [ -z "$pathspec_from_file" ] && [ "$pathspec_file_nul" = y ]
 then
-	printf 'Option "--pathspec-file-nul" is not valid without "--pathspec-from-file".\n' 1>&2
+	printf 'error: option '\''--pathspec-file-nul'\'' is not valid without '\''--pathspec-from-file'\''\n' 1>&2
 	exit 1
 fi
 
diff --git a/lib/git-istash/git-istash-pop b/lib/git-istash/git-istash-pop
--- a/lib/git-istash/git-istash-pop
+++ b/lib/git-istash/git-istash-pop
@@ -26,20 +26,23 @@ save_data() {
 load_stash_data() { # subcommand
 	if [ "$(wc -l <"$stash_data_file")" -ne 1 ]
 	then
-		printf 'fatal: "%s" should have exactly 1 line.\n' "$stash_data_file" 1>&2
+		printf 'fatal: '\''git istash pop'\'' seems to be running but the data files are broken\n' 1>&2
+		printf 'fatal: '\''%s'\'' doesn'\''t have exactly 1 line\n' "$stash_data_file" 1>&2
 		print_quit_hint "$1"
 		return 1
 	fi
 	stash="$(cat "$stash_data_file")"
 	if ! [ "$stash" -eq "$stash" ] 2>/dev/null || [ "$stash" -lt 0 ]
 	then
-		printf 'fatal: "%s" doesn'\''t contain a positive integer.\n' "$stash_data_file" 1>&2
+		printf 'fatal: '\''git istash pop'\'' seems to be running but the data files are broken\n' 1>&2
+		printf 'fatal: '\''%s'\'' doesn'\''t contain a positive integer\n' "$stash_data_file" 1>&2
 		print_quit_hint "$1"
 		return 1
 	fi
 	if [ "$stash" -ge "$(git rev-list --walk-reflogs --count --ignore-missing refs/stash)" ]
 	then
-		printf 'fatal: "%s" says "%i" but there is no such stash.\n' "$stash_data_file" "$stash" 1>&2
+		printf 'fatal: '\''git istash pop'\'' seems to be running but the data files are broken\n' 1>&2
+		printf 'fatal: '\''%s'\'' contains an invalid stash number\n' "$stash_data_file" 1>&2
 		print_quit_hint "$1"
 		return 1
 	fi
@@ -66,7 +69,7 @@ check_stash_for_pop() {
 	then
 		:
 	else
-		printf 'error: Only stash entries can be popped.\n' 1>&2
+		printf 'error: can only pop '\''refs/stash'\'' or entries of its reflog\n' 1>&2
 		return 1
 	fi
 }
@@ -75,11 +78,11 @@ print_quit_hint() { # subcommand
 	printf_color 2 '\033[33m'
 	if [ "$1" = 'pop' ]
 	then
-		printf 'hint: Fix the problem and finish that operation before starting a new one\n'
+		printf 'hint: fix the problem and finalize that operation before starting a new one\n'
 	else
-		printf 'hint: Fix the problem and finish that operation before starting "git istash pop"\n'
+		printf 'hint: fix the problem and finalize that operation before starting '\''istash pop'\''\n'
 	fi
-	printf 'hint: or run "git istash %s --quit" to forcefully cancel it.\n' "$1"
+	printf 'hint: or run '\''git istash --quit'\'' to forcefully cancel it\n'
 	printf_color 2 '\033[39m'
 } 1>&2
 
@@ -90,8 +93,8 @@ check_data_files() { # resume abort quit
 			if [ "$1" = y ] || [ "$2" = y ] || [ "$3" = y ] ; then return 0 ; fi
 			{
 				printf_color 2 '\033[33m'
-				printf 'fatal: "git istash %s" is already in progress?\n' "$operation_in_progress"
-				printf 'hint: Use "git istash %s --continue" or "git istash %s --abort".\n' "$operation_in_progress" "$operation_in_progress"
+				printf 'error: '\''git istash %s'\'' is already in progress\n' "$operation_in_progress"
+				printf 'hint: use '\''git istash --continue'\'' or '\''git istash --abort'\''\n'
 				printf_color 2 '\033[39m'
 			} 1>&2
 			return 1
@@ -100,7 +103,7 @@ check_data_files() { # resume abort quit
 			if [ "$2" = y ] || [ "$3" = y ] ; then return 0 ; fi
 			{
 				printf_color 2 '\033[33m'
-				printf 'error: There is currently a istash %s in progress.\n' "$operation_in_progress"
+				printf 'error: there is currently '\''git istash %s'\'' in progress\n' "$operation_in_progress"
 				printf_color 2 '\033[39m'
 			} 1>&2
 			return 1
@@ -112,12 +115,15 @@ check_data_files() { # resume abort quit
 				printf_color 2 '\033[31m'
 				if [ -f "$(make_target_data_file_path)" ]
 				then
-					printf 'fatal: "git istash %s" seems to be in progress but "%s" is missing!\n' "$operation_in_progress" "$(make_working_dir_sha_file_path)"
+					printf 'fatal: '\''git istash %s'\'' seems to be running but the data files are broken\n' "$operation_in_progress" 1>&2
+					printf 'fatal: '\''%s'\'' is missing\n' "$(make_working_dir_sha_file_path)"
 				elif [ -f "$(make_working_dir_sha_file_path)" ]
 				then
-					printf 'fatal: "git istash %s" seems to be in progress but "%s" is missing!\n' "$operation_in_progress" "$(make_target_data_file_path)"
+					printf 'fatal: '\''git istash %s'\'' seems to be running but the data files are broken\n' "$operation_in_progress" 1>&2
+					printf 'fatal: '\''%s'\'' is missing\n' "$(make_target_data_file_path)"
 				else
-					printf 'fatal: "git istash %s" seems to be in progress but "%s" and "%s" are missing!\n' "$operation_in_progress" "$(make_target_data_file_path)" "$(make_working_dir_sha_file_path)"
+					printf 'fatal: '\''git istash %s'\'' seems to be running but the data files are broken\n' "$operation_in_progress" 1>&2
+					printf 'fatal: '\''%s'\'' and '\''%s'\'' are missing!' "$(make_target_data_file_path)" "$(make_working_dir_sha_file_path)"
 				fi
 				printf_color 2 '\033[33m'
 				printf_color 2 '\033[39m'
@@ -127,7 +133,7 @@ check_data_files() { # resume abort quit
 			;;
 		nothing)
 			if [ "$1" = n ] && [ "$2" = n ] && [ "$3" = n ] ; then return 0 ; fi
-			printf 'fatal: No istash pop in progress?\n' 1>&2
+			printf 'error: no istash pop in progress\n' 1>&2
 			return 1
 			;;
 	esac
@@ -225,22 +231,22 @@ do
 done
 if [ $continue_set = y ] && [ $abort_set = y ] && [ $quit_set = y ]
 then
-	printf 'error: You can choose continue, abort or quit at your discretion but the rule is that you can only have one.\n' 1>&2
+	printf 'error: you can choose continue, abort or quit at your discretion but the rule is that you can only have one\n' 1>&2
 	exit 1
 fi
 if [ $abort_set = y ] && [ $quit_set = y ]
 then
-	printf 'error: Either abort or quit; there is no middle road.\n' 1>&2
+	printf 'error: either abort or quit; there is no middle road\n' 1>&2
 	exit 1
 fi
 if [ $continue_set = y ] && [ $abort_set = y ]
 then
-	printf 'error: Unclear whether to continue aborting or to abort continuing.\n' 1>&2
+	printf 'error: unclear whether to continue aborting or to abort continuing\n' 1>&2
 	exit 1
 fi
 if [ $continue_set = y ] && [ $quit_set = y ]
 then
-	printf 'error: Unclear whether to continue quitting or to quit continuing.\n' 1>&2
+	printf 'error: unclear whether to continue quitting or to quit continuing\n' 1>&2
 	exit 1
 fi
 
diff --git a/lib/git-istash/git-istash-push b/lib/git-istash/git-istash-push
--- a/lib/git-istash/git-istash-push
+++ b/lib/git-istash/git-istash-push
@@ -29,7 +29,7 @@ print_help() {
 }
 
 check_pathspec_for_implicit_push() ( # args...
-	getopt_result="$(getopt -o"-$getopt_short_options" --long="$getopt_long_options" -n"$(basename "$0")" -ssh -- "$@")"
+	getopt_result="$(getopt -o"-$getopt_short_options" --long="$getopt_long_options" -n'error' -ssh -- "$@")"
 	eval set -- "$getopt_result"
 	while [ $# -ne 0 ]
 	do
@@ -53,8 +53,8 @@ check_pathspec_for_implicit_push() ( # args...
 				shift
 			fi
 		else
-			printf 'fatal: unexpected token "%s"\n' "$1" 1>&2
-			printf 'fatal: pathspec for an implicit "push" command must be preceded by "--"\n' 1>&2
+			printf 'error: subcommand wasn'\''t specified; '\''push'\'' can'\''t be assumed due to unexpected token '\''%s'\''\n' "$1" 1>&2
+			printf 'hint: pathspecs for an implicit '\''push'\'' subcommand must be preceded by '\''--'\''\n' 1>&2
 			exit 1
 		fi
 	done
