Added Git version check to the `bin/git-istash`
It shows a readable error message when the version of `git` is not
sufficient to run `istash`.

diff --git a/bin/git-istash b/bin/git-istash
--- a/bin/git-istash
+++ b/bin/git-istash
@@ -2,6 +2,8 @@
 
 set -e
 
+min_git_version='2.42.0'
+
 print_help() {
 	printf 'git istash - Improved version of "git stash" that can handle more corner cases.\n'
 	printf '    (See "--help" of individual sub-commands.)\n'
@@ -25,6 +27,7 @@ print_help() {
 print_version() {
 	printf 'git-istash version 1.1.2\n'
 	printf 'Author: Piotr Siupa\n'
+	printf 'Requires Git in version at least %s\n' "$min_git_version"
 }
 
 run_subcommand() { # subcommand [arguments...]
@@ -84,6 +87,13 @@ elif [ "$1" = '--version' ] || [ "$2" = '--version' ]
 then
 	print_version
 	exit 0
+fi
+
+git_version="$(git --version | head -n 1 | grep -Eo '\<\S+$')"
+if ! printf '%s' "$git_version" | grep -Exq '2\.(4[2-9]|[5-9][0-9]|[0-9]{3,})(\.[0-9]+(\.[0-9]+)?)?'
+then
+	printf 'fatal: the current Git version (%s) is less than minimum required (%s)\n' "$git_version" "$min_git_version" 1>&2
+	exit 1
 fi
 
 if [ $# -eq 0 ] || printf '%s' "$1" | grep -Eq '^-'
