Fixed a few rough edges created in the refactoring
This has mostly to do with both scripts acknowledging that the other one
exists and handle gracefully situations then the other one is in
progress. (With an appropriate exception for calling `git-istash-apply`
from `git-istash-pop`.)

diff --git a/scripts/git-istash-apply b/scripts/git-istash-apply
--- a/scripts/git-istash-apply
+++ b/scripts/git-istash-apply
@@ -11,42 +11,43 @@ print_help() {
 	printf '   or: git istash-apply (-c | --continue | --abort)\n'
 }
 
+get_sub_command_name() { #
+	if [ "$is_pop" = n ]
+	then
+		printf 'apply'
+	else
+		printf 'pop'
+	fi
+}
+
 save_data() {
 	target_data="$(if [ "$orphan" = y ] ; then printf '~' ; fi ; printf '%s' "$target")"
 	printf '%s\n' "$target_data" >"$target_data_file"
 }
-does_data_exits() {
-	[ -f "$target_data_file" ]
-}
 load_data() {
-	if ! does_data_exits
-	then
-		printf 'fatal: No istash in progress?\n' 1>&2
-		exit 1
-	elif [ "$(wc -l <"$target_data_file")" -ne 1 ]
+	if [ "$(wc -l <"$target_data_file")" -ne 1 ]
 	then
 		printf 'fatal: "%s" is should contain exactly 1 line.\n' "$target_data_file" 1>&2
 		exit 1
+	fi
+	target="$(cat "$target_data_file")"
+	if printf '%s' "$target" | grep -q '^~'
+	then
+		orphan=y
+		target="$(printf '%s' "$target" | cut -c2-)"
 	else
-		target="$(cat "$target_data_file")"
-		if printf '%s' "$target" | grep -q '^~'
-		then
-			orphan=y
-			target="$(printf '%s' "$target" | cut -c2-)"
-		else
-			orphan=n
-		fi
-		if ! git rev-parse --quiet --verify "$target^{commit}" 1>/dev/null
-		then
-			printf 'fatal: "%s" says "%s" but there is no such commit.\n' "$target_data_file" "$target" 1>&2
-			exit 1
-		fi
-		if [ "$orphan" = n ] && [ "$(git rev-parse "$target")" = "$target" ]
-		then
-			detached=y
-		else
-			detached=n
-		fi
+		orphan=n
+	fi
+	if ! git rev-parse --quiet --verify "$target^{commit}" 1>/dev/null
+	then
+		printf 'fatal: "%s" says "%s" but there is no such commit.\n' "$target_data_file" "$target" 1>&2
+		exit 1
+	fi
+	if [ "$orphan" = n ] && [ "$(git rev-parse "$target")" = "$target" ]
+	then
+		detached=y
+	else
+		detached=n
 	fi
 }
 delete_data() {
@@ -63,9 +64,10 @@ end_with_rebase_problem() {
 	then
 		printf '\e[33m'
 	fi
+	sub_command_name="$(get_sub_command_name)"
 	printf 'hint: Disregard all hints above about using "git rebase".\n' 1>&2
-	printf 'hint: Use "git istash-apply --continue" after fixing conflicts.\n' 1>&2
-	printf 'hint: To abort and get back to the state before "git istash-apply", run "git istash-apply --abort".\n' 1>&2
+	printf 'hint: Use "git istash-%s --continue" after fixing conflicts.\n' "$sub_command_name" 1>&2
+	printf 'hint: To abort and get back to the state before "git istash-%s", run "git istash-%s --abort".\n' "$sub_command_name" "$sub_command_name" 1>&2
 	if is_color_allowed 2
 	then
 		printf '\e[39m'
@@ -107,14 +109,62 @@ end_with_success() {
 	printf '\nSuccessfully applied the stash\n'
 }
 
-check_repository_state() {
-	if [ -n "$(git status --porcelain)" ]
-	then
-		# There are still are some limitations.
-		printf 'error: There are uncommitted changes in the working directory.\n' 1>&2
-		printf 'error: Please commit or stash them.\n' 1>&2
-		exit 1
-	fi
+check_data_files() { # resume
+	if [ "$is_pop" = y ] ; then return 0 ; fi
+	case "$(find_data_files)" in
+		pop)
+			printf '\n' 1>&2
+			if is_color_allowed 2
+			then
+				printf '\e[33m'
+			fi
+			printf 'fatal: "git istash-pop" is already in progress?\n' 1>&2
+			printf 'hint: Finish that operation before starting "git istash-apply".\n' 1>&2
+			if is_color_allowed 2
+			then
+				printf '\e[39m'
+			fi
+			exit 1
+			;;
+		apply)
+			if [ "$1" = y ] ; then return 0 ; fi
+			if is_color_allowed 2
+			then
+				printf '\e[33m'
+			fi
+			printf 'fatal: "git istash-apply" is already in progress?\n' 1>&2
+			printf 'hint: Use "git istash-apply --continue" or "git istash-apply --abort".\n' 1>&2
+			if is_color_allowed 2
+			then
+				printf '\e[39m'
+			fi
+			exit 1
+			;;
+		error)
+			printf '\n' 1>&2
+			if is_color_allowed 2
+			then
+				printf '\e[31m'
+			fi
+			printf 'fatal: "git istash-pop" seems to be in progress but "%s" is missing!\n' "$target_data_file" 1>&2
+			if is_color_allowed 2
+			then
+				printf '\e[33m'
+			fi
+			printf 'hint: Fix the problem and finish that operation before starting "git istash-apply"\n' 1>&2
+			printf 'hint: or remove the file "%s" to manually cancel it.\n' "$(make_stash_data_file_path)" 1>&2
+			if is_color_allowed 2
+			then
+				printf '\e[39m'
+			fi
+			exit 1
+			;;
+		nothing)
+			if [ "$1" = n ] ; then return 0 ; fi
+			printf 'fatal: No istash-apply in progress?\n' 1>&2
+			exit 1
+			;;
+	esac
 }
 
 untangle_git_stash() {
@@ -132,21 +182,7 @@ untangle_git_stash() {
 
 do_start() { # args...
 	check_args_for_apply 1 "$@"
-	if does_data_exits
-	then
-		printf '\n' 1>&2
-		if is_color_allowed 2
-		then
-			printf '\e[33m'
-		fi
-		printf 'fatal: Istash already in progress?\n' 1>&2
-		printf 'hint: Use "git istash --continue" or "git istash --abort".\n' 1>&2
-		if is_color_allowed 2
-		then
-			printf '\e[39m'
-		fi
-		exit 1
-	fi
+	check_data_files n
 	check_repository_state
 	find_stash "$@"
 	find_current_branch
@@ -167,6 +203,7 @@ do_start() { # args...
 
 do_continue() { # args...
 	check_args_for_apply 0 "$@"
+	check_data_files y
 	load_data
 	
 	if git -c 'core.editor=true' rebase --continue
@@ -179,6 +216,7 @@ do_continue() { # args...
 
 do_abort() { # args...
 	check_args_for_apply 0 "$@"
+	check_data_files y
 	load_data
 	
 	git rebase --abort || true  # Errors are ignored because if rebase is not in progress, we still want to try to restore HEAD.
@@ -213,8 +251,13 @@ do_abort() { # args...
 		then
 			printf '\e[33m'
 		fi
-		printf 'hint: Fix problems and rerun "git istash-apply --abort"\n' 1>&2
-		printf 'hint: or delete the file "%s" to cancel manually.\n' "$target_data_file" 1>&2
+		printf 'hint: Fix problems and rerun "git istash-%s --abort"\n' "$(get_sub_command_name)" 1>&2
+		if [ "$is_pop" = n ]
+		then
+			printf 'hint: or delete the file "%s" to cancel manually.\n' "$target_data_file" 1>&2
+		else
+			printf 'hint: or delete the files "%s" and "%s" to cancel manually.\n' "$(make_stash_data_file_path)" "$target_data_file" 1>&2
+		fi
 		if is_color_allowed 2
 		then
 			printf '\e[39m'
@@ -235,10 +278,11 @@ do_unstash() { # args...
 	fi
 }
 
-getopt_result="$(getopt -o'hc' --long='help,continue,abort' -n"$(basename "$0")" -- "$@")"
+getopt_result="$(getopt -o'hc' --long='help,continue,abort,called-from-pop' -n"$(basename "$0")" -- "$@")"
 eval set -- "$getopt_result"
 continue_set=n
 abort_set=n
+is_pop=n
 while true
 do
 	case "$1" in
@@ -251,6 +295,9 @@ do
 		;;
 	--abort)
 		abort_set=y
+		;;
+	--called-from-pop)
+		is_pop=y
 		;;
 	--)
 		shift
@@ -266,5 +313,5 @@ then
 fi
 
 cd "$(git rev-parse --show-toplevel)"
-target_data_file="$(make_data_file_path 'target')"
+target_data_file="$(make_target_data_file_path)"
 do_unstash "$@"
diff --git a/scripts/git-istash-pop b/scripts/git-istash-pop
--- a/scripts/git-istash-pop
+++ b/scripts/git-istash-pop
@@ -14,30 +14,22 @@ print_help() {
 save_data() {
 	printf '%s\n' "$stash" >"$stash_data_file"
 }
-does_data_exits() {
-	[ -f "$stash_data_file" ]
-}
 load_data() {
-	if ! does_data_exits
-	then
-		printf 'fatal: No istash in progress?\n' 1>&2
-		exit 1
-	elif [ "$(wc -l <"$stash_data_file")" -ne 1 ]
+	if [ "$(wc -l <"$stash_data_file")" -ne 1 ]
 	then
 		printf 'fatal: "%s" is should contain exactly 1 line.\n' "$stash_data_file" 1>&2
 		exit 1
-	else
-		stash="$(cat "$stash_data_file")"
-		if ! [ "$stash" -eq "$stash" ] 2>/dev/null || [ "$stash" -lt 0 ]
-		then
-			printf 'fatal: "%s" doesn'\''t contain a positive integer.\n' "$stash_data_file" 1>&2
-			exit 1
-		fi
-		if [ "$stash" -ge "$(git rev-list --walk-reflogs --count --ignore-missing refs/stash)" ]
-		then
-			printf 'fatal: "%s" says "%i" but there is no such stash.\n' "$stash_data_file" "$stash" 1>&2
-			exit 1
-		fi
+	fi
+	stash="$(cat "$stash_data_file")"
+	if ! [ "$stash" -eq "$stash" ] 2>/dev/null || [ "$stash" -lt 0 ]
+	then
+		printf 'fatal: "%s" doesn'\''t contain a positive integer.\n' "$stash_data_file" 1>&2
+		exit 1
+	fi
+	if [ "$stash" -ge "$(git rev-list --walk-reflogs --count --ignore-missing refs/stash)" ]
+	then
+		printf 'fatal: "%s" says "%i" but there is no such stash.\n' "$stash_data_file" "$stash" 1>&2
+		exit 1
 	fi
 }
 delete_data() {
@@ -54,27 +46,71 @@ end_with_success() {
 	printf '\nSuccessfully popped the stash\n'
 }
 
+check_data_files() { # resume
+	case "$(find_data_files)" in
+		pop)
+			if [ "$1" = y ] ; then return 0 ; fi
+			printf '\n' 1>&2
+			if is_color_allowed 2
+			then
+				printf '\e[33m'
+			fi
+			printf 'fatal: "git istash-pop" is already in progress?\n' 1>&2
+			printf 'hint: Use "git istash-pop --continue" or "git istash-pop --abort".\n' 1>&2
+			if is_color_allowed 2
+			then
+				printf '\e[39m'
+			fi
+			exit 1
+			;;
+		apply)
+			printf '\n' 1>&2
+			if is_color_allowed 2
+			then
+				printf '\e[33m'
+			fi
+			printf 'fatal: "git istash-apply" is already in progress?\n' 1>&2
+			printf 'hint: Finish that operation before starting "git istash-pop".\n' 1>&2
+			if is_color_allowed 2
+			then
+				printf '\e[39m'
+			fi
+			exit 1
+			;;
+		error)
+			printf '\n' 1>&2
+			if is_color_allowed 2
+			then
+				printf '\e[31m'
+			fi
+			printf 'fatal: "git istash-pop" seems to be in progress but "%s" is missing!\n' "$target_data_file" 1>&2
+			if is_color_allowed 2
+			then
+				printf '\e[33m'
+			fi
+			printf 'hint: Fix the problem and finish that operation before starting a new one\n' 1>&2
+			printf 'hint: or remove the file "%s" to manually cancel it.\n' "$(make_stash_data_file_path)" 1>&2
+			if is_color_allowed 2
+			then
+				printf '\e[39m'
+			fi
+			exit 1
+			;;
+		nothing)
+			if [ "$1" = n ] ; then return 0 ; fi
+			printf 'fatal: No istash-pop in progress?\n' 1>&2
+			exit 1
+			;;
+	esac
+}
+
 run_apply() { # args...
-	sh "$(dirname "$0")/git-istash-apply" "$@" || exit 1
+	sh "$(dirname "$0")/git-istash-apply" --called-from-pop "$@" || exit 1
 }
 
 do_start() { # args...
 	check_args_for_pop 1 "$@"
-	if does_data_exits
-	then
-		printf '\n' 1>&2
-		if is_color_allowed 2
-		then
-			printf '\e[33m'
-		fi
-		printf 'fatal: Istash already in progress?\n' 1>&2
-		printf 'hint: Use "git istash --continue" or "git istash --abort".\n' 1>&2
-		if is_color_allowed 2
-		then
-			printf '\e[39m'
-		fi
-		exit 1
-	fi
+	check_data_files n
 	check_repository_state
 	find_stash "$@"
 	save_data
@@ -84,6 +120,7 @@ do_start() { # args...
 
 do_continue() { # args...
 	check_args_for_pop 0 "$@"
+	check_data_files y
 	load_data
 	run_apply --continue
 	end_with_success
@@ -91,6 +128,7 @@ do_continue() { # args...
 
 do_abort() { # args...
 	check_args_for_pop 0 "$@"
+	check_data_files y
 	load_data
 	run_apply --abort
 	delete_data
@@ -139,5 +177,5 @@ then
 fi
 
 cd "$(git rev-parse --show-toplevel)"
-stash_data_file="$(make_data_file_path 'stash')"
+stash_data_file="$(make_stash_data_file_path)"
 do_pop "$@"
