Saving only the stash number to the data file
It complicates the script a little but it simplifies the file which is
preferable. If popped stash is just a commit and not a real stash, it's
not saved at all and the file is empty. (This will change soon anyway
when pop and apply will be split into separate commands.)

diff --git a/scripts/git-istash b/scripts/git-istash
--- a/scripts/git-istash
+++ b/scripts/git-istash
@@ -23,7 +23,12 @@ find_data_files() {
 	target_data_file="$git_dir/ISTASH_TARGET"
 }
 save_data() {
-	printf '%s\n' "$stash" >"$stash_data_file"
+	if [ "$stash" -eq "$stash" ] 2>/dev/null
+	then
+		printf '%s\n' "$stash" >"$stash_data_file"
+	else
+		touch "$stash_data_file"
+	fi
 	target_data="$(if [ "$orphan" = y ] ; then printf '~' ; fi ; printf '%s' "$target")"
 	printf '%s\n' "$target_data" >"$target_data_file"
 }
@@ -44,7 +49,7 @@ load_data() {
 	then
 		printf 'fatal: No istash in progress?\n' 1>&2
 		exit 1
-	elif [ "$(wc -l <"$stash_data_file")" -ne 1 ]
+	elif [ "$(wc -l <"$stash_data_file")" -gt 1 ]
 	then
 		printf 'fatal: "%s" is should contain exactly 1 line.\n' "$stash_data_file" 1>&2
 		exit 1
@@ -132,7 +137,7 @@ end_with_success() {
 	git add -- .
 	git restore --source="$other_changes_hash" -- . || true
 	delete_data
-	if printf '%s' "$stash" | grep -xq 'stash@{[0-9]\+}'
+	if [ "$stash" -eq "$stash" ]
 	then
 		git stash drop "$stash"
 	fi
@@ -149,63 +154,76 @@ check_repository_state() {
 	fi
 }
 
+get_stash_commit() { # stash
+	if [ "$1" -eq "$1" ] 2>/dev/null
+	then
+		printf '%s' "stash@{$1}"
+	else
+		printf '%s' "$1"
+	fi
+}
+
 find_stash() { # [arg]
 	if [ $# -eq 0 ] || [ "$1" = 'stash' ]
 	then
-		stash='stash@{0}'
+		stash=0
 	elif [ "$1" -eq "$1" ] 2>/dev/null
 	then
 		if [ "$1" -ge 0 ]
 		then
-			stash="stash@{$1}"
+			stash=$1
 		else
-			stash="stash@{$(($(git rev-list --walk-reflogs --count --ignore-missing refs/stash) + $1))}"
+			stash=$(($(git rev-list --walk-reflogs --count --ignore-missing refs/stash) + $1))
 		fi
 	elif printf '%s' "$1" | grep -xq 'stash\^{/.*}'
 	then
 		stash_text="$(printf '%s' "$1" | sed 's/^stash\^{\/\(.*\)}$/\1/')"
 		stash_hash="$(git rev-list --walk-reflogs --grep-reflog="$stash_text" --ignore-missing refs/stash | head -n1)"
-		stash="stash@{$(($(git rev-list --walk-reflogs refs/stash | grep -Fxn "$stash_hash" | cut -d: -f1) - 1))}"
+		stash="$(($(git rev-list --walk-reflogs refs/stash | grep -Fxn "$stash_hash" | cut -d: -f1) - 1))"
+	elif printf '%s' "$1" | grep -xq 'stash@{[0-9]\+}'
+	then
+		stash="$(printf '%s' "$1" | sed 's/^stash@{\(.*\)}$/\1/')"
 	else
 		stash="$1"
 	fi
 	
-	if ! git rev-parse --quiet --verify "$stash^{commit}" 1>/dev/null
+	stash_commit="$(get_stash_commit "$stash")"
+	if ! git rev-parse --quiet --verify "$stash_commit^{commit}" 1>/dev/null
 	then
-		printf 'fatal: There is no commit "%s".\n' "$stash" 1>&2
+		printf 'fatal: There is no commit "%s".\n' "$stash_commit" 1>&2
 		exit 1
 	fi
-	parents_num="$(git rev-list --no-walk --count "$stash^@")"
+	parents_num="$(git rev-list --no-walk --count "$stash_commit^@")"
 	if [ "$parents_num" -lt 2 ] || [ "$parents_num" -gt 3 ]
 	then
-		printf 'fatal: "%s" should have 2 or 3 parents to be a stash.\n' "$stash" 1>&2
+		printf 'fatal: "%s" should have 2 or 3 parents to be a stash.\n' "$stash_commit" 1>&2
 		exit 1
 	fi
-	if [ "$parents_num" -eq 3 ] && [ "$(git rev-list --no-walk --count "$stash^3^@")" -ne 0 ]
+	if [ "$parents_num" -eq 3 ] && [ "$(git rev-list --no-walk --count "$stash_commit^3^@")" -ne 0 ]
 	then
-		printf 'fatal: "%s^3" should have no parents to be a part of a stash.\n' "$stash" 1>&2
+		printf 'fatal: "%s^3" should have no parents to be a part of a stash.\n' "$stash_commit" 1>&2
 		exit 1
 	fi
-	if [ "$(git rev-list --no-walk --count "$stash^2^@")" -ne 1 ]
+	if [ "$(git rev-list --no-walk --count "$stash_commit^2^@")" -ne 1 ]
 	then
-		printf 'fatal: The commit "%s^2" should have one parent to be a part of a stash.\n' "$stash" 1>&2
+		printf 'fatal: The commit "%s^2" should have one parent to be a part of a stash.\n' "$stash_commit" 1>&2
 		exit 1
 	fi
-	if [ "$(git rev-parse "$stash^1")" != "$(git rev-parse "$stash^2^")" ]
+	if [ "$(git rev-parse "$stash_commit^1")" != "$(git rev-parse "$stash_commit^2^")" ]
 	then
-		printf 'fatal: The commit "%s^1" should be the parent of "%s^2" to be a part of a stash.\n' "$stash" "$stash" 1>&2
+		printf 'fatal: The commit "%s^1" should be the parent of "%s^2" to be a part of a stash.\n' "$stash_commit" "$stash_commit" 1>&2
 		exit 1
 	fi
 	correct_commit_msgs=0
-	if [ "$parents_num" -eq 3 ] && git rev-list --format='%B' --max-count=1 "$stash^3" | head -n 2 | tail -n 1 | grep -q '^untracked files on .\+:'
+	if [ "$parents_num" -eq 3 ] && git rev-list --format='%B' --max-count=1 "$stash_commit^3" | head -n 2 | tail -n 1 | grep -q '^untracked files on .\+:'
 	then
 		correct_commit_msgs=$((correct_commit_msgs + 1))
 	fi
-	if git rev-list --format='%B' --max-count=1 "$stash^2" | head -n 2 | tail -n 1 | grep -q '^index on .\+:'
+	if git rev-list --format='%B' --max-count=1 "$stash_commit^2" | head -n 2 | tail -n 1 | grep -q '^index on .\+:'
 	then
 		correct_commit_msgs=$((correct_commit_msgs + 1))
 	fi
-	if git rev-list --format='%B' --max-count=1 "$stash" | head -n 2 | tail -n 1 | grep -q '^\(WIP on\|On\) .\+:'
+	if git rev-list --format='%B' --max-count=1 "$stash_commit" | head -n 2 | tail -n 1 | grep -q '^\(WIP on\|On\) .\+:'
 	then
 		correct_commit_msgs=$((correct_commit_msgs + 1))
 	fi
@@ -213,9 +231,9 @@ find_stash() { # [arg]
 	then
 		if [ $correct_commit_msgs -eq 0 ]
 		then
-			printf 'error: "%s"'\''s commits don'\''t have correct messages for stash.\n' "$stash" 1>&2
+			printf 'error: "%s"'\''s commits don'\''t have correct messages for stash.\n' "$stash_commit" 1>&2
 		else
-			printf 'error: some of "%s"'\'' commits don'\''t have correct messages for stash.\n' "$stash" 1>&2
+			printf 'error: some of "%s"'\'' commits don'\''t have correct messages for stash.\n' "$stash_commit" 1>&2
 		fi
 		printf 'error: It may not be a stash entry or it may be damaged.\n'
 		exit 1
@@ -240,12 +258,13 @@ find_current_branch() {
 }
 
 untangle_git_stash() {
-	git switch --detach "$stash^2"
-	git merge --ff-only --squash "$stash"
-	if git rev-parse "$stash^3" 1>/dev/null 2>&1
+	stash_commit="$(get_stash_commit "$stash")"
+	git switch --detach "$stash_commit^2"
+	git merge --ff-only --squash "$stash_commit"
+	if git rev-parse "$stash_commit^3" 1>/dev/null 2>&1
 	then
-		git ls-tree -r --name-only "$stash^3" -z \
-		| xargs -r0 -- git restore --source="$stash^3" --
+		git ls-tree -r --name-only "$stash_commit^3" -z \
+		| xargs -r0 -- git restore --source="$stash_commit^3" --
 		git add .
 	fi
 	git commit --no-edit --no-verify --allow-empty
