Split data file into 2 with one piece of data each
They are also named analogically to files made by normal git commands.

diff --git a/scripts/git-istash b/scripts/git-istash
--- a/scripts/git-istash
+++ b/scripts/git-istash
@@ -17,33 +17,44 @@ print_help() {
 	printf '   or: git istash (-c | --continue | --abort)\n'
 }
 
-find_data_file() {
+find_data_files() {
 	git_dir="$(git rev-parse --git-dir)"
-	data_file="$git_dir/istash"
+	stash_data_file="$git_dir/ISTASH_STASH"
+	target_data_file="$git_dir/ISTASH_TARGET"
 }
 save_data() {
-	printf '%s\n%s\n' \
-		"$stash" \
-		"$(if [ "$orphan" = y ] ; then printf '~' ; fi ; printf '%s' "$target")" \
-		>"$data_file"
+	printf '%s\n' "$stash" >"$stash_data_file"
+	target_data="$(if [ "$orphan" = y ] ; then printf '~' ; fi ; printf '%s' "$target")"
+	printf '%s\n' "$target_data" >"$target_data_file"
 }
 does_data_exits() {
-	test -f "$data_file"
+	if [ -f "$stash_data_file" ] && [ -f "$target_data_file" ]
+	then
+		return 0
+	elif [ -f "$stash_data_file" ] || [ -f "$target_data_file" ]
+	then
+		printf 'fatal: One of the data files is missing.\n' 1>&2
+		exit 1
+	else
+		return 1
+	fi
 }
 load_data() {
 	if ! does_data_exits
 	then
 		printf 'fatal: No istash in progress?\n' 1>&2
 		exit 1
-	elif [ "$(wc -l <"$data_file")" -ne 2 ]
+	elif [ "$(wc -l <"$stash_data_file")" -ne 1 ]
 	then
-		printf 'fatal: "%s" is should contain 2 lines.\n' "$data_file" 1>&2
+		printf 'fatal: "%s" is should contain exactly 1 line.\n' "$stash_data_file" 1>&2
+		exit 1
+	elif [ "$(wc -l <"$target_data_file")" -ne 1 ]
+	then
+		printf 'fatal: "%s" is should contain exactly 1 line.\n' "$target_data_file" 1>&2
 		exit 1
 	else
-		{
-			read -r stash
-			read -r target
-		} <"$data_file"
+		read -r stash <"$stash_data_file"
+		read -r target <"$target_data_file"
 		if printf '%s' "$target" | grep -q '^~'
 		then
 			orphan=y
@@ -60,7 +71,7 @@ load_data() {
 	fi
 }
 delete_data() {
-	rm -f "$data_file"
+	rm -f "$stash_data_file" "$target_data_file"
 }
 
 check_args() { # max_free_args args...
@@ -94,19 +105,19 @@ end_with_success() {
 	staged_changes_hash="$(git rev-parse HEAD~)"
 	if [ "$orphan" = n ] && [ "$(git rev-parse HEAD~2)" != "$(git rev-parse "$target")" ]
 	then
-		printf 'Fatal: HEAD is not in correct position after rebasing.\n' 1>&2
+		printf 'fatal: HEAD is not in correct position after rebasing.\n' 1>&2
 		exit 1
 	fi
 	if [ "$orphan" = 'y' ]
 	then
 		if [ "$(git rev-list --no-walk --count HEAD~2^@)" -ne 0 ]
 		then
-			printf 'Fatal: Target branch is not an orphan anymore.\n' 1>&2
+			printf 'fatal: Target branch is not an orphan anymore.\n' 1>&2
 			exit 1
 		fi
 		if [ -n "$(git ls-tree -r --name-only HEAD~2)" ]
 		then
-			printf 'Fatal: The empty commit created for the command is not empty.\n' 1>&2
+			printf 'fatal: The empty commit created for the command is not empty.\n' 1>&2
 			exit 1
 		fi
 		git branch --delete --force "$target"
@@ -324,7 +335,7 @@ do_abort() { # args...
 			printf '\e[33m'
 		fi
 		printf 'hint: Fix problems and rerun "git istash --abort"\n' 1>&2
-		printf 'hint: or delete file "%s" to cancel manually.\n' "$data_file" 1>&2
+		printf 'hint: or delete files "%s" and "%s" to cancel manually.\n' "$stash_data_file" "$target_data_file" 1>&2
 		if is_color_allowed 2
 		then
 			printf '\e[39m'
@@ -376,5 +387,5 @@ then
 fi
 
 cd "$(git rev-parse --show-toplevel)"
-find_data_file
+find_data_files
 do_unstash "$@"
