Renamed "unstash" to "istash" ("improved stash")

diff --git a/scripts/git-istash b/scripts/git-istash
--- a/scripts/git-istash
+++ b/scripts/git-istash
@@ -11,15 +11,15 @@ is_color_allowed() { # stream_num
 }
 
 show_help() {
-	printf 'git-unstash - Improved version of "git stash pop" the can handle conflicts.\n'
+	printf 'git-istash - Improved version of "git stash pop" the can handle conflicts.\n'
 	printf '\n'
-	printf 'usage: git unstash [<stash>]\n'
-	printf '   or: git unstash (-c | --continue | --abort)\n'
+	printf 'usage: git istash [<stash>]\n'
+	printf '   or: git istash (-c | --continue | --abort)\n'
 }
 
 find_data_file() {
 	git_dir="$(git rev-parse --git-dir)"
-	data_file="$git_dir/unstash"
+	data_file="$git_dir/istash"
 }
 save_data() {
 	printf '%s\n%s\n%s\n' "$stash" "$current_branch" "$detached" >"$data_file"
@@ -30,7 +30,7 @@ does_data_exits() {
 load_data() {
 	if ! does_data_exits
 	then
-		printf 'fatal: No unstash in progress?\n' 1>&2
+		printf 'fatal: No istash in progress?\n' 1>&2
 		exit 1
 	elif [ "$(wc -l <"$data_file")" -ne 3 ]
 	then
@@ -54,7 +54,7 @@ check_args() { # max_free_args args...
 	if [ $# -gt "$max_free_args" ]
 	then
 		printf 'error: Too many arguments.\n' 1>&2
-		printf 'error: Type "git unstash --help" for more information.\n' 1>&2
+		printf 'error: Type "git istash --help" for more information.\n' 1>&2
 		exit 1
 	fi
 }
@@ -66,8 +66,8 @@ end_with_rebase_problem() {
 		printf '\e[33m'
 	fi
 	printf 'hint: Disregard all hints above about using "git rebase".\n' 1>&2
-	printf 'hint: Use "git unstash --continue" after fixing conflicts.\n' 1>&2
-	printf 'hint: To abort and get back to the state before "git unstash", run "git unstash --abort".\n' 1>&2
+	printf 'hint: Use "git istash --continue" after fixing conflicts.\n' 1>&2
+	printf 'hint: To abort and get back to the state before "git istash", run "git istash --abort".\n' 1>&2
 	if is_color_allowed 2
 	then
 		printf '\e[39m'
@@ -82,7 +82,7 @@ end_with_success() {
 	fi
 	delete_data
 	git stash drop "$stash"
-	printf '\nSuccessfully unstashed the stash\n' 1>&2
+	printf '\nSuccessfully istashed the stash\n' 1>&2
 }
 
 check_repository_state() {
@@ -198,8 +198,8 @@ do_start() { # args...
 		then
 			printf '\e[33m'
 		fi
-		printf 'fatal: Unstash already in progress?\n' 1>&2
-		printf 'hint: Use "git unstash --continue" or "git unstash --abort".\n' 1>&2
+		printf 'fatal: Istash already in progress?\n' 1>&2
+		printf 'hint: Use "git istash --continue" or "git istash --abort".\n' 1>&2
 		if is_color_allowed 2
 		then
 			printf '\e[39m'
@@ -241,7 +241,7 @@ do_abort() { # args...
 	if git switch --quiet "$current_branch"
 	then
 		delete_data
-		printf 'Aborted "git unstash"\n' 1>&2
+		printf 'Aborted "git istash"\n' 1>&2
 	else
 		printf '\n' 1>&2
 		printf 'fatal: Failed to restore HEAD.\n' 1>&2
@@ -249,7 +249,7 @@ do_abort() { # args...
 		then
 			printf '\e[33m'
 		fi
-		printf 'hint: Fix problems and rerun "git unstash --abort"\n' 1>&2
+		printf 'hint: Fix problems and rerun "git istash --abort"\n' 1>&2
 		printf 'hint: or delete file "%s" to cancel manually.\n' "$data_file" 1>&2
 		if is_color_allowed 2
 		then
