Added standalone mode to the script `get_options`
It can now be used as a standalone program, similarly to `getopt`.
It's still sourced in git-istash scripts but this script may be useful
in other projects and the modification was easy to do.
(The biggest challenge was to write a help text for it.)

(Also, increased delays on a few tests because they were flaky.)

diff --git a/lib/git-istash/get_options b/lib/git-istash/get_options
--- a/lib/git-istash/get_options
+++ b/lib/git-istash/get_options
@@ -1,21 +1,18 @@
+#!/usr/bin/env sh
+
 # Fully POSIX option parser inspired by GNU getopt, although not strictly compatible with it.
 # The small deviations of the output (from what getopt with similar options would produce with similar settings) are there because of how get_options is used by the script for which it was written.
 # The user should still get exactly what their expect from a GNU-like program.
+# It can be either sourced or used as a standalone script.
 
+# Escapes stdin in a way that it will be "eval"ed as a single string in a POSIX shell.
 escape_for_shell() {
 	printf \'
 	sed -E s/\'/\'\\\\\'\'/g
 	printf \'
 }
 
-# The descriptions of short and long options have the same general syntax as for "getopt" (except for prefixes "-" and "+" which aren't supported here).
-# Options:
-# -P - Posixly correct mode - treat everything after the first non-option as non-options (and preserve the first "==" if it's after a non-option).
-# -R - Don't reorder entries by placing all non-option arguments after "--" (normalize only) and don't generate an additional "--" if not present. (Normally options are shuffled like by "getopt".)
-# -U - Like -P but treat unknown options as non-options and never skip the first "--". (Good for pre-parsing when not all options are known yet.) WARNING: it assumes that there is no ambiguous abbreviations between known and unknown option names!
-# Returns 0 on success.
-# Returns 1 on failure to parse options.
-# Returns 2 on error with the usage of the function itself.
+# See "print_help" for usage.
 get_options() ( # [-P | -R | -U] short_options_string long_options_string [argument...]
 	set -eu
 	
@@ -236,3 +233,65 @@ get_options() ( # [-P | -R | -U] short_options_string long_options_string [argum
 		printf '%s' "$non_option_args"
 	fi
 )
+
+if [ "$(basename "$0")" = 'get_options' ]
+then
+	set -eu
+	
+	print_help() {
+		printf 'A fully POSIX script for parsing options in program arguments.\n'
+		printf 'It is meant to be a portable alternative when "getopt" may not be available,\nor in some rare parsing scenarios that are not supported by "getopt".\n'
+		#shellcheck disable=SC2016
+		printf 'The output should be generally the same as in "getopt" with analogous settings\nand it is meant to be used with "eval" to set positional parameters in shell,\nlike this: eval set -- "$output_of_get_options".\n'
+		printf '\n'
+		printf 'Usage:\tget_options [-P | -R | -U] <short_opts_descr> <long_opts_descr> [arg...]\n'
+		printf '   or:\tget_options [-h | --help | -V | --version]    (Only in standalone mode.)\n'
+		printf '(Ironically, the order of arguments has to be exactly as described.)\n'
+		printf 'Options:\n'
+		printf '    -P\t- Posixly correct mode - after the first encountered non-option, treat\n\t  everything else as non-options. Preserve the first "--" if it'\''s after\n\t  a non-option.\n'
+		printf '    -R\t- Don'\''t reorder entries by placing all non-option arguments after "--"\n\t  (normalize only) and don'\''t generate an additional "--" if not present.\n'
+		printf '    -U\t- Like -P but treat unrecognized options as non-options and never skip\n\t  the first "--" even if it isn'\''t preceded by any non-options.\n\t  (Good for pre-parsing when not all options are known yet.)\n\t  WARNING: it assumes that there is no ambiguous abbreviations between\n\t  known and unknown option names!\n'
+		printf 'Standalone mode options:\n'
+		printf '    -h, --help\t\t- Print this help text end exit.\n'
+		printf '    -V, --version\t- Print version information and exit.\n'
+		printf '\n'
+		printf '<short_opts_descr> - a string describing all allowed short options.\n'
+		printf 'Short option string contains a list of options names as individual characters,\nwithout separators. '
+		printf 'A special character ":" may follow another character to\nsymbolize that the option has an argument.\n'
+		printf 'Characters "-" and ":" may not be used as short option names.\n'
+		printf '(Weird characters such as whitespaces aren'\''t tested and may not work.)\n'
+		printf 'E.g. "abc:d" defines options "-a", "-b", "-c" and "-d", where "-c" takes an\nargument and the other options don'\''t.\n'
+		printf '(An empty string means that short options are not allowed.)\n'
+		printf '\n'
+		printf '<long_opts_descr> - a string describing all known long options.\n'
+		printf 'Long options are a list of option names separated with ",". '
+		printf 'A special character\n":" may be placed at the end of an option name to symbolize that the option has\nan argument. '
+		printf '(Optional arguments are not supported.)\n'
+		printf 'Characters ":" and "," may not be used in long option names.\n'
+		printf '(Weird characters such as whitespaces aren'\''t tested and may not work.)\n'
+		printf 'E.g. "foo,bar:,baz" defines options "--foo", "--bar" and "--baz", where "--bar"\ntakes an argument and the other options don'\''t.\n'
+		printf '(An empty string means that long options are not allowed.)\n'
+		printf '\n'
+		printf 'Exit values:\n'
+		printf ' - 0 - Success.\n'
+		printf ' - 1 - Parse error. (normal error)\n'
+		printf ' - 2 - Error with the usage of the get_options itself. (fatal error)\n'
+	}
+	
+	print_version() {
+		printf 'get_options version 1.0.0\n'
+		printf 'Author: Piotr Siupa'
+	}
+	
+	if [ "${1-}" = '-h' ] || [ "${1-}" = '--help' ]
+	then
+		print_help
+		exit 0
+	elif [ "${1-}" = '-V' ] || [ "${1-}" = '--version' ]
+	then
+		print_version
+		exit 0
+	fi
+	
+	get_options "$@"
+fi
