Improved parsing for the options `--color`
Also, added a few more tests for things implemented earlier and fixed
some problems that would be revealed by the next commit.

diff --git a/lib/git-istash/git-istash-commons b/lib/git-istash/git-istash-commons
--- a/lib/git-istash/git-istash-commons
+++ b/lib/git-istash/git-istash-commons
@@ -19,6 +19,20 @@ printf_color() { # stream_num args...
 }
 
 set_color_for_all() { # value
+	set -- "$1" "$(printf '%s' "$1" | tr 'A-Z\n' 'a-zX')"
+	if printf '%s' "$2" | grep -Exq 'a(lways)?|y(es)?|t(rue)?|affirmative|1'
+	then
+		set -- 'always'
+	elif printf '%s' "$2" | grep -Exq 'n(ever)?|no|f(alse)?|negative|0'
+	then
+		set -- 'never'
+	elif printf '%s' "$2" | grep -Exq 'auto|d(efault)?|(terminal|tty)(-only)?|magic' # yeah, this is overdoing it, whatever, it's fun
+	then
+		set -- 'auto'
+	else
+		printf 'error: `%s'\'' is not a valid color boolean' "$1" 1>&2
+		return 1
+	fi
 	if [ -z "${GIT_CONFIG_COUNT-}" ]
 	then
 		GIT_CONFIG_COUNT=0
