Checking operations in progress for applying
Added tests for applying operations (`apply` & `pop`) to see if they
correctly exit with an error (without breaking anything) when one of the
following operations is currently in progress: another `istash apply` or
`istash pop`, `rebase`, `merge`, `cherry-pick`, `revert` or `bisect`.

diff --git a/lib/git-istash/git-istash-commons b/lib/git-istash/git-istash-commons
--- a/lib/git-istash/git-istash-commons
+++ b/lib/git-istash/git-istash-commons
@@ -70,6 +70,11 @@ check_other_git_commands_state() {
 		printf 'error: There is currently a merge in progress.\n' 1>&2
 		return 1
 	fi
+	if [ -e "$git_dir/BISECT_START" ]
+	then
+		printf 'error: There is currently a bisect in progress.\n' 1>&2
+		return 1
+	fi
 }
 
 get_stash_commit() { # stash
