Added color to error messages with `fatal:`

diff --git a/lib/git-istash/git-istash-apply b/lib/git-istash/git-istash-apply
--- a/lib/git-istash/git-istash-apply
+++ b/lib/git-istash/git-istash-apply
@@ -41,10 +41,10 @@ save_data() {
 load_target_data() { # subcommand
 	if [ "$(wc -l <"$target_data_file")" -ne 1 ]
 	then
-		printf 'fatal: '\''git istash %s'\'' seems to be in progress but the data files are broken\n' "$(get_sub_command_name)" 1>&2
-		printf 'fatal: '\''%s'\'' doesn'\''t have exactly 1 line\n' "$target_data_file" 1>&2
+		printf_fatal \''git istash %s'\'' seems to be in progress but the data files are broken\n' "$(get_sub_command_name)"
+		printf_fatal \''%s'\'' doesn'\''t have exactly 1 line\n' "$target_data_file"
 		print_broken_operation_hint "$1"
-		return 1
+		fatal
 	fi
 	current_branch="$(cat "$target_data_file")"
 	if printf '%s' "$current_branch" | grep -qE '^~'
@@ -56,10 +56,10 @@ load_target_data() { # subcommand
 	fi
 	if ! git rev-parse --quiet --verify "$current_branch^{commit}" 1>/dev/null
 	then
-		printf 'fatal: '\''git istash %s'\'' seems to be in progress but the data files are broken\n' "$(get_sub_command_name)" 1>&2
-		printf 'fatal: '\''%s'\'' contains an invalid commit hash\n' "$target_data_file" 1>&2
+		printf_fatal \''git istash %s'\'' seems to be in progress but the data files are broken\n' "$(get_sub_command_name)"
+		printf_fatal \''%s'\'' contains an invalid commit hash\n' "$target_data_file"
 		print_broken_operation_hint "$1"
-		return 1
+		fatal
 	fi
 	if [ "$curr_branch_type" != 'orphan' ] && [ "$(git rev-parse "$current_branch")" = "$current_branch" ]
 	then
@@ -69,18 +69,18 @@ load_target_data() { # subcommand
 load_working_dir_data() { # subcommand
 	if [ "$(wc -l <"$working_dir_sha_file")" -ne 1 ]
 	then
-		printf 'fatal: '\''git istash %s'\'' seems to be in progress but the data files are broken\n' "$(get_sub_command_name)" 1>&2
-		printf 'fatal: '\''%s'\'' doesn'\''t have exactly 1 line\n' "$working_dir_sha_file" 1>&2
+		printf_fatal \''git istash %s'\'' seems to be in progress but the data files are broken\n' "$(get_sub_command_name)"
+		printf_fatal \''%s'\'' doesn'\''t have exactly 1 line\n' "$working_dir_sha_file"
 		print_broken_operation_hint "$1"
-		return 1
+		fatal
 	fi
 	working_dir_changes_sha="$(cat "$working_dir_sha_file")"
 	if ! git rev-parse --quiet --verify "$working_dir_changes_sha^{commit}" 1>/dev/null
 	then
-		printf 'fatal: '\''git istash %s'\'' seems to be in progress but the data files are broken\n' "$(get_sub_command_name)" 1>&2
-		printf 'fatal: '\''%s'\'' contains an invalid commit hash\n' "$working_dir_sha_file" 1>&2
+		printf_fatal \''git istash %s'\'' seems to be in progress but the data files are broken\n' "$(get_sub_command_name)"
+		printf_fatal \''%s'\'' contains an invalid commit hash\n' "$working_dir_sha_file"
 		print_broken_operation_hint "$1"
-		return 1
+		fatal
 	fi
 }
 load_data() { # subcommand
@@ -117,8 +117,7 @@ end_with_success() {
 	if { [ "$curr_branch_type" != 'orphan' ] && [ "$(git rev-parse HEAD~6)" != "$(git rev-parse "$current_branch")" ] ; } \
 		|| { [ "$curr_branch_type" = 'orphan' ] && [ "$(git rev-list --no-walk --count HEAD~6^@)" != '0' ] ; }
 	then
-		printf 'fatal: HEAD is not in the correct position after rebasing\n' 1>&2
-		return 1
+		fatal 'HEAD is not in the correct position after rebasing\n'
 	fi
 	untracked_changes_sha="$(git rev-parse HEAD~0)"
 	non_staged_changes_sha="$(git rev-parse HEAD~2)"
@@ -128,8 +127,7 @@ end_with_success() {
 			if [ -n "$(git ls-tree -r --name-only HEAD~6)" ]
 			then
 				# This error is untested because it's hard to come up with a scenario so contrived that it would occur.
-				printf 'fatal: the empty commit created for the command is not empty\n' 1>&2
-				return 1
+				fatal 'the empty commit created for the command is not empty\n'
 			fi
 			git branch --quiet --delete --force "$current_branch"
 			git switch --quiet --orphan "$current_branch"
@@ -267,9 +265,9 @@ do_continue() { # args...
 		end_with_rebase_problem
 	else
 		exec 3>&-
-		printf '%s\n' "$stderr" 1>&2
 		git reset --quiet --soft HEAD~
-		return 1
+		printf '%s' "$stderr" | color_fatal 1>&2
+		fatal
 	fi
 	exec 3>&-
 }
@@ -279,7 +277,11 @@ do_abort() { # args...
 	check_data_files y n
 	load_data "$(get_sub_command_name)"
 	
-	git rebase --abort || true  # Errors are ignored because if rebase is not in progress, we still want to try to restore HEAD.
+	error_message="$(git rebase --abort 2>&1 || true)"  # Errors are ignored because if rebase is not in progress, we still want to try to restore HEAD.
+	if [ -n "$error_message" ]
+	then
+		printf '%s\n' "$error_message" | color_fatal 1>&2
+	fi
 	git reset --quiet --hard
 	succeeded_switch=n
 	exec 3>&1
@@ -317,12 +319,10 @@ do_abort() { # args...
 			printf 'Successfully aborted '\''git istash pop'\''\n'
 		fi 1>&2
 	else
-		{
-			printf 'fatal: failed to restore HEAD to initial position\n'
-			printf '%s\n' "$error_message"
-			print_broken_operation_hint '--abort'
-		} 1>&2
-		return 1
+		printf_fatal 'failed to restore HEAD to initial position\n'
+		printf '%s\n' "$error_message" | color_fatal 1>&2
+		print_broken_operation_hint '--abort'
+		fatal
 	fi
 }
 
@@ -381,6 +381,7 @@ do
 		;;
 	--color)
 		shift
+		set_color_for_all "$1"
 		;;
 	-c|--continue)
 		continue_set=y
diff --git a/lib/git-istash/git-istash-commons b/lib/git-istash/git-istash-commons
--- a/lib/git-istash/git-istash-commons
+++ b/lib/git-istash/git-istash-commons
@@ -18,6 +18,30 @@ printf_color() { # stream_num args...
 	fi
 }
 
+set_color_for_all() { # value
+	if [ -z "${GIT_CONFIG_COUNT-}" ]
+	then
+		GIT_CONFIG_COUNT=0
+	fi
+	export GIT_CONFIG_COUNT
+	#shellcheck disable=SC2034,SC2041
+	for key in 'color.istash.error'
+	do
+		eval "GIT_CONFIG_KEY_$GIT_CONFIG_COUNT"='"$key"'
+		export "GIT_CONFIG_KEY_$GIT_CONFIG_COUNT"
+		eval "GIT_CONFIG_VALUE_$GIT_CONFIG_COUNT"='"$1"'
+		export "GIT_CONFIG_VALUE_$GIT_CONFIG_COUNT"
+		GIT_CONFIG_COUNT=$((GIT_CONFIG_COUNT + 1))
+	done
+	#TODO The code below is a temporary solution to make tests pass while not all colors are yet implemented.
+	#TODO It needs to be replaced with something robust before a merge to master.
+	eval "GIT_CONFIG_KEY_$GIT_CONFIG_COUNT"='color.ui'
+	export "GIT_CONFIG_KEY_$GIT_CONFIG_COUNT"
+	eval "GIT_CONFIG_VALUE_$GIT_CONFIG_COUNT"='never'
+	export "GIT_CONFIG_VALUE_$GIT_CONFIG_COUNT"
+	GIT_CONFIG_COUNT=$((GIT_CONFIG_COUNT + 1))
+}
+
 is_color_enabled() { # config_variable...
 	if [ $# -eq 0 ]
 	then
@@ -55,6 +79,30 @@ color_lines() { # default_value config_variable
 	color_escape_code="$(get_color "$@")"
 	reset_escape_code="$(git config --get-color '' 'reset')"
 	sed -E "/./s/^.*\$/$color_escape_code&$reset_escape_code/"
+}
+
+color_fatal() {
+	if is_color_enabled 'color.istash.error' 'color.istash'
+	then
+		color_lines 'bold red' 'color.istash.error.fatal' #TODO default to a normal error (after it's implemented)
+	else
+		cat
+	fi
+}
+
+printf_fatal() { # arg...
+	#shellcheck disable=SC2059
+	printf "$@" \
+	| sed -E '/./s/^/fatal: /' \
+	| color_fatal
+} 1>&2
+
+fatal() { # arg...
+	if [ $# -ne 0 ]
+	then
+		printf_fatal "$@"
+	fi
+	return 1
 }
 
 if command -v od 1>/dev/null 2>&1
@@ -169,15 +217,15 @@ print_error_for_data_files_check() { # current_operation called_operation
 	if printf '%s\n' "$1" | grep -E -q '^error-'
 	then
 		operation_in_progress="$(printf '%s' "$1" | tail -c +7)"
-		printf 'fatal: '\''git istash %s'\'' seems to be in progress but the data files are broken\n' "$operation_in_progress"
+		printf_fatal \''git istash %s'\'' seems to be in progress but the data files are broken\n' "$operation_in_progress"
 		if [ -f "$(make_target_data_file_path)" ]
 		then
-			printf 'fatal: '\''%s'\'' is missing\n' "$(make_working_dir_sha_file_path)"
+			printf_fatal \''%s'\'' is missing\n' "$(make_working_dir_sha_file_path)"
 		elif [ -f "$(make_working_dir_sha_file_path)" ]
 		then
-			printf 'fatal: '\''%s'\'' is missing\n' "$(make_target_data_file_path)"
+			printf_fatal \''%s'\'' is missing\n' "$(make_target_data_file_path)"
 		else
-			printf 'fatal: '\''%s'\'' and '\''%s'\'' are missing\n' "$(make_target_data_file_path)" "$(make_working_dir_sha_file_path)"
+			printf_fatal \''%s'\'' and '\''%s'\'' are missing\n' "$(make_target_data_file_path)" "$(make_working_dir_sha_file_path)"
 		fi
 		print_broken_operation_hint "$2"
 	elif [ "$1" != 'nothing' ]
@@ -246,23 +294,19 @@ check_stash() { # stash
 	parents_num="$(git rev-list --no-walk --count "$stash_commit^@")"
 	if [ "$parents_num" -lt 2 ] || [ "$parents_num" -gt 3 ]
 	then
-		printf 'fatal: '\''%s'\'' doesn'\''t have 2 or 3 parents required to be a stash\n' "$stash_commit" 1>&2
-		return 1
+		fatal \''%s'\'' doesn'\''t have 2 or 3 parents required to be a stash\n' "$stash_commit"
 	fi
 	if [ "$parents_num" -eq 3 ] && [ "$(git rev-list --no-walk --count "$stash_commit^3^@")" -ne 0 ]
 	then
-		printf 'fatal: '\''%s^3'\'' have parents unlike in a stash\n' "$stash_commit" 1>&2
-		return 1
+		fatal \''%s^3'\'' have parents unlike in a stash\n' "$stash_commit"
 	fi
 	if [ "$(git rev-list --no-walk --count "$stash_commit^2^@")" -ne 1 ]
 	then
-		printf 'fatal: '\''%s^2'\'' doesn'\''t have one parent like in a stash\n' "$stash_commit" 1>&2
-		return 1
+		fatal \''%s^2'\'' doesn'\''t have one parent like in a stash\n' "$stash_commit"
 	fi
 	if [ "$(git rev-parse "$stash_commit^1")" != "$(git rev-parse "$stash_commit^2^")" ]
 	then
-		printf 'fatal: '\''%s^1'\'' isn'\''t the parent of '\''%s^2'\'' like in a stash\n' "$stash_commit" "$stash_commit" 1>&2
-		return 1
+		fatal \''%s^1'\'' isn'\''t the parent of '\''%s^2'\'' like in a stash\n' "$stash_commit" "$stash_commit"
 	fi
 	correct_commit_msgs=0
 	if [ "$parents_num" -eq 3 ] && git rev-list --format='%B' --max-count=1 "$stash_commit^3" | head -n 2 | tail -n 1 | grep -qE '^untracked files on .+:'
@@ -279,9 +323,9 @@ check_stash() { # stash
 	fi
 	if [ $correct_commit_msgs -ne "$parents_num" ]
 	then
-		printf 'fatal: some of '\''%s'\'' commits don'\''t have correct messages for a stash\n' "$stash_commit" 1>&2
-		printf 'fatal: it may not be a stash entry or it may be damaged\n' 1>&2
-		return 1
+		printf_fatal 'some of '\''%s'\'' commits don'\''t have correct messages for a stash\n' "$stash_commit"
+		printf_fatal 'it may not be a stash entry or it may be damaged\n'
+		fatal
 	fi
 }
 
@@ -316,8 +360,7 @@ set_getopt_options_from_make_command() {
 	if [ "$(printf '%s\n' "$getopt_short_options" | wc -l)" -ne 1 ] || [ "$(printf '%s\n' "$getopt_long_options" | wc -l)" -ne 1 ]
 	then
 		# Not tested because it cannot be triggered. It's here in a case something gets broken by a future change.
-		printf 'fatal: cannot determine if there is option '\''-h'\'' in the arguments\n' 1>&2
-		return 1
+		fatal 'cannot determine if there is option '\''-h'\'' in the arguments\n'
 	fi
 }
 
