Added output assertions for tests in "creating"
This is the same situation as with the previous commit for "applying".
For now the assertions are added mostly just to pass. A few most obvious
cases of wrong outputs were fixed (mostly when it was printing much more
than needed due to outputs of git commands called internally).
However, the output was generally left close to what it was before. It
will be rethought in the later commits as the point of this one is just
to establish existence of the necessary assertions in the tests.
(And this alone is a lot of work; so much that it is being spread onto
multiple commits.)

diff --git a/lib/git-istash/git-istash-commons b/lib/git-istash/git-istash-commons
--- a/lib/git-istash/git-istash-commons
+++ b/lib/git-istash/git-istash-commons
@@ -98,9 +98,10 @@ check_other_git_commands_state() {
 }
 
 check_data_files() {
-	if [ "$(find_data_files)" != 'nothing' ]
+	current_operation="$(find_data_files)"
+	if [ "$current_operation" != 'nothing' ]
 	then
-		printf 'error: There is currently an istash apply in progress.\n' 1>&2
+		printf 'error: There is currently an istash %s in progress.\n' "$current_operation" 1>&2
 		return 1
 	fi
 }
