Removed dashes in the command names
This was accomplished by adding a new command `git-istash` that calls
the other two commands. The other commands are now hidden in from user
in `scripts/.git-istash/`.

diff --git a/scripts/.git-istash/git-istash-apply b/scripts/.git-istash/git-istash-apply
--- a/scripts/.git-istash/git-istash-apply
+++ b/scripts/.git-istash/git-istash-apply
@@ -2,13 +2,13 @@
 
 set -e
 
-. "$(dirname "$0")/.git-istash/git-istash-commons"
+. "$(dirname "$0")/git-istash-commons"
 
 print_help() {
-	printf 'git-istash-apply - Improved version of "git stash apply" that can handle\n    conflicts.\n'
+	printf 'git istash apply - Improved version of "git stash apply" that can handle\n    conflicts.\n'
 	printf '\n'
-	printf 'usage: git istash-apply [<stash>]\n'
-	printf '   or: git istash-apply (-c | --continue | --abort)\n'
+	printf 'usage: git istash apply [<stash>]\n'
+	printf '   or: git istash apply (-c | --continue | --abort)\n'
 }
 
 get_sub_command_name() { #
@@ -53,7 +53,7 @@ delete_data() {
 }
 
 check_args_for_apply() { # max_free_args args...
-	check_args 'istash-apply' "$@"
+	check_args 'istash apply' "$@"
 }
 
 end_with_rebase_problem() {
@@ -64,8 +64,8 @@ end_with_rebase_problem() {
 	fi
 	sub_command_name="$(get_sub_command_name)"
 	printf 'hint: Disregard all hints above about using "git rebase".\n' 1>&2
-	printf 'hint: Use "git istash-%s --continue" after fixing conflicts.\n' "$sub_command_name" 1>&2
-	printf 'hint: To abort and get back to the state before "git istash-%s", run "git istash-%s --abort".\n' "$sub_command_name" "$sub_command_name" 1>&2
+	printf 'hint: Use "git istash %s --continue" after fixing conflicts.\n' "$sub_command_name" 1>&2
+	printf 'hint: To abort and get back to the state before "git istash %s", run "git istash %s --abort".\n' "$sub_command_name" "$sub_command_name" 1>&2
 	if is_color_allowed 2
 	then
 		printf '\e[39m'
@@ -118,8 +118,8 @@ check_data_files() { # resume
 			then
 				printf '\e[33m'
 			fi
-			printf 'fatal: "git istash-pop" is already in progress?\n' 1>&2
-			printf 'hint: Finish that operation before starting "git istash-apply".\n' 1>&2
+			printf 'fatal: "git istash pop" is already in progress?\n' 1>&2
+			printf 'hint: Finish that operation before starting "git istash apply".\n' 1>&2
 			if is_color_allowed 2
 			then
 				printf '\e[39m'
@@ -132,8 +132,8 @@ check_data_files() { # resume
 			then
 				printf '\e[33m'
 			fi
-			printf 'fatal: "git istash-apply" is already in progress?\n' 1>&2
-			printf 'hint: Use "git istash-apply --continue" or "git istash-apply --abort".\n' 1>&2
+			printf 'fatal: "git istash apply" is already in progress?\n' 1>&2
+			printf 'hint: Use "git istash apply --continue" or "git istash apply --abort".\n' 1>&2
 			if is_color_allowed 2
 			then
 				printf '\e[39m'
@@ -146,12 +146,12 @@ check_data_files() { # resume
 			then
 				printf '\e[31m'
 			fi
-			printf 'fatal: "git istash-pop" seems to be in progress but "%s" is missing!\n' "$target_data_file" 1>&2
+			printf 'fatal: "git istash pop" seems to be in progress but "%s" is missing!\n' "$target_data_file" 1>&2
 			if is_color_allowed 2
 			then
 				printf '\e[33m'
 			fi
-			printf 'hint: Fix the problem and finish that operation before starting "git istash-apply"\n' 1>&2
+			printf 'hint: Fix the problem and finish that operation before starting "git istash apply"\n' 1>&2
 			printf 'hint: or remove the file "%s" to manually cancel it.\n' "$(make_stash_data_file_path)" 1>&2
 			if is_color_allowed 2
 			then
@@ -161,7 +161,7 @@ check_data_files() { # resume
 			;;
 		nothing)
 			if [ "$1" = n ] ; then return 0 ; fi
-			printf 'fatal: No istash-apply in progress?\n' 1>&2
+			printf 'fatal: No istash apply in progress?\n' 1>&2
 			return 1
 			;;
 	esac
@@ -261,7 +261,7 @@ do_abort() { # args...
 		then
 			printf '\e[33m'
 		fi
-		printf 'hint: Fix problems and rerun "git istash-%s --abort"\n' "$(get_sub_command_name)" 1>&2
+		printf 'hint: Fix problems and rerun "git istash %s --abort"\n' "$(get_sub_command_name)" 1>&2
 		if [ "$is_pop" = n ]
 		then
 			printf 'hint: or delete the file "%s" to cancel manually.\n' "$target_data_file" 1>&2
@@ -276,7 +276,7 @@ do_abort() { # args...
 	fi
 }
 
-do_unstash() { # args...
+do_apply() { # args...
 	if [ "$continue_set" = y ]
 	then
 		do_continue "$@"
@@ -324,4 +324,4 @@ fi
 
 cd "$(git rev-parse --show-toplevel)"
 target_data_file="$(make_target_data_file_path)"
-do_unstash "$@"
+do_apply "$@"
diff --git a/scripts/.git-istash/git-istash-pop b/scripts/.git-istash/git-istash-pop
--- a/scripts/.git-istash/git-istash-pop
+++ b/scripts/.git-istash/git-istash-pop
@@ -2,13 +2,13 @@
 
 set -e
 
-. "$(dirname "$0")/.git-istash/git-istash-commons"
+. "$(dirname "$0")/git-istash-commons"
 
 print_help() {
-	printf 'git-istash-pop - Improved version of "git stash pop" that can handle conflicts.\n'
+	printf 'git istash pop - Improved version of "git stash pop" that can handle conflicts.\n'
 	printf '\n'
-	printf 'usage: git istash-pop [<stash>]\n'
-	printf '   or: git istash-pop (-c | --continue | --abort)\n'
+	printf 'usage: git istash pop [<stash>]\n'
+	printf '   or: git istash pop (-c | --continue | --abort)\n'
 }
 
 save_data() {
@@ -37,7 +37,7 @@ delete_data() {
 }
 
 check_args_for_pop() { # max_free_args args...
-	check_args 'istash-pop' "$@"
+	check_args 'istash pop' "$@"
 }
 
 end_with_success() {
@@ -65,8 +65,8 @@ check_data_files() { # resume
 			then
 				printf '\e[33m'
 			fi
-			printf 'fatal: "git istash-pop" is already in progress?\n' 1>&2
-			printf 'hint: Use "git istash-pop --continue" or "git istash-pop --abort".\n' 1>&2
+			printf 'fatal: "git istash pop" is already in progress?\n' 1>&2
+			printf 'hint: Use "git istash pop --continue" or "git istash pop --abort".\n' 1>&2
 			if is_color_allowed 2
 			then
 				printf '\e[39m'
@@ -79,8 +79,8 @@ check_data_files() { # resume
 			then
 				printf '\e[33m'
 			fi
-			printf 'fatal: "git istash-apply" is already in progress?\n' 1>&2
-			printf 'hint: Finish that operation before starting "git istash-pop".\n' 1>&2
+			printf 'fatal: "git istash apply" is already in progress?\n' 1>&2
+			printf 'hint: Finish that operation before starting "git istash pop".\n' 1>&2
 			if is_color_allowed 2
 			then
 				printf '\e[39m'
@@ -93,7 +93,7 @@ check_data_files() { # resume
 			then
 				printf '\e[31m'
 			fi
-			printf 'fatal: "git istash-pop" seems to be in progress but "%s" is missing!\n' "$(make_target_data_file)" 1>&2
+			printf 'fatal: "git istash pop" seems to be in progress but "%s" is missing!\n' "$(make_target_data_file)" 1>&2
 			if is_color_allowed 2
 			then
 				printf '\e[33m'
@@ -108,7 +108,7 @@ check_data_files() { # resume
 			;;
 		nothing)
 			if [ "$1" = n ] ; then return 0 ; fi
-			printf 'fatal: No istash-pop in progress?\n' 1>&2
+			printf 'fatal: No istash pop in progress?\n' 1>&2
 			return 1
 			;;
 	esac
